### ISSUE TITLE
[GCE] Happened to panic runtime error, Therefore not added user, pem file is not copied to the local

### ISSUE THREAD

**Issue by zchee** [docker/machine#1066]
Happened to panic runtime error when launch google compute engine instance.

This problem happen in the HEAD build.
Doesn't seem occurred in the pre-release 0.2.0 version.

It seems instance is created successfully.
but, **`.pem` is not copied to the local.**
Therefore, docker-machine {ssh, env} commands are not available.

Duplicate https://github.com/docker/machine/issues/771 ?

See result.
```
./docker-machine_darwin-amd64 create docker-machine-google --driver google --google-disk-size "50" --google-disk-type "pd-ssd" --google-machine-ty
pe "f1-micro" --google-project xxxxx-xxxxx-12345 --google-zone "asia-east1-c"
INFO[0000] Opening auth URL in browser.
INFO[0000] https://accounts.google.com/o/oauth2/auth?client_id=....
INFO[0000] If the URL doesn't open please open it manually and copy the code here.
Enter code: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
INFO[0006] Got code: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
INFO[0006] Saving token in /Users/zchee/.docker/machine/machines/docker-machine-google/gce_token
INFO[0006] Creating host...
INFO[0007] Generating SSH Key
INFO[0008] Creating instance.
INFO[0008] Creating firewall rule.
INFO[0013] Waiting for Instance...
INFO[0093] Uploading SSH Key
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x103a1b]

goroutine 16 [running]:
runtime.panic(0x6d3880, 0xb2dd84)
        /usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/docker/machine/drivers/google.(*ComputeUtil).createInstance(0x208c6b080, 0x208c322d0, 0x0, 0x0)
        /go/src/github.com/docker/machine/drivers/google/compute_util.go:218 +0xe2b
github.com/docker/machine/drivers/google.(*Driver).Create(0x208c322d0, 0x0, 0x0)
        /go/src/github.com/docker/machine/drivers/google/google.go:196 +0x257
github.com/docker/machine/libmachine.(*Host).Create(0x208c4d860, 0x7fff5fbfee6d, 0x15, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/host.go:101 +0x70
github.com/docker/machine/libmachine.(*Machine).Create(0x208d12680, 0x7fff5fbfee6d, 0x15, 0x208cacd30, 0x6, 0x208cb7440, 0x2208c36060, 0x208c78b40, 0x0, 0x0, ...)
        /go/src/github.com/docker/machine/libmachine/machine.go:59 +0x565
github.com/docker/machine/commands.cmdCreate(0x208c78b40)
        /go/src/github.com/docker/machine/commands/create.go:82 +0xa7b
github.com/codegangsta/cli.Command.Run(0x7792b0, 0x6, 0x0, 0x0, 0x7c0650, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2
github.com/codegangsta/cli.(*App).Run(0x208c4c4e0, 0x208c32000, 0xf, 0xf, 0x0, 0x0)
        /go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea
main.main()
        /go/src/github.com/docker/machine/main.go:73 +0x5a3

goroutine 19 [finalizer wait, 1 minutes]:
runtime.park(0x151a0, 0xb31d38, 0xb2fe49)
        /usr/src/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xb31d38, 0xb2fe49)
        /usr/src/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/src/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 1 minutes]:
os/signal.loop()
        /usr/src/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 27 [IO wait, 1 minutes]:
net.runtime_pollWait(0x2208c374f8, 0x72, 0x0)
        /usr/src/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0x208ca06f0, 0x72, 0x0, 0x0)
        /usr/src/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0x208ca06f0, 0x0, 0x0)
        /usr/src/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0x208ca0690, 0x208c7bc00, 0x400, 0x400, 0x0, 0x2208c353a0, 0x23)
        /usr/src/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0x208c66090, 0x208c7bc00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/src/go/src/pkg/net/net.go:122 +0xe7
crypto/tls.(*block).readFromUntil(0x208cfdf80, 0x2208c37880, 0x208c66090, 0x5, 0x0, 0x0)
        /usr/src/go/src/pkg/crypto/tls/conn.go:451 +0xd9
crypto/tls.(*Conn).readRecord(0x208cccb00, 0x17, 0x0, 0x0)
        /usr/src/go/src/pkg/crypto/tls/conn.go:536 +0x1ff
crypto/tls.(*Conn).Read(0x208cccb00, 0x208cbc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/src/go/src/pkg/crypto/tls/conn.go:901 +0x16a
net/http.noteEOFReader.Read(0x2208c417e0, 0x208cccb00, 0x208c6a318, 0x208cbc000, 0x1000, 0x1000, 0xb45fe0, 0x0, 0x0)
        /usr/src/go/src/pkg/net/http/transport.go:1203 +0x72
net/http.(*noteEOFReader).Read(0x208fd2b40, 0x208cbc000, 0x1000, 0x1000, 0x208c52170, 0x0, 0x0)
        <autogenerated>:124 +0xca
bufio.(*Reader).fill(0x208c28de0)
        /usr/src/go/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).Peek(0x208c28de0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/pkg/bufio/bufio.go:132 +0x101
net/http.(*persistConn).readLoop(0x208c6a2c0)
        /usr/src/go/src/pkg/net/http/transport.go:782 +0x95
created by net/http.(*Transport).dialConn
        /usr/src/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 24 [select, 1 minutes]:
net.func·019()
        /usr/src/go/src/pkg/net/dnsclient_unix.go:184 +0x2ab
created by net.loadConfig
        /usr/src/go/src/pkg/net/dnsclient_unix.go:212 +0x153

goroutine 28 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0x208c6a2c0)
        /usr/src/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
        /usr/src/go/src/pkg/net/http/transport.go:601 +0x957

goroutine 32 [runnable]:
net/http.(*persistConn).readLoop(0x208c6b130)
        /usr/src/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
        /usr/src/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 33 [select]:
net/http.(*persistConn).writeLoop(0x208c6b130)
        /usr/src/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
        /usr/src/go/src/pkg/net/http/transport.go:601 +0x957
```

**Comment by zchee** [comment]
Where I was confirmed now, user also does not appear to have been added, I could not be a login docker-user even normal ssh command.
If this is my of environmental problems, forgive me please.

**Comment by jeffmendoza** [comment]
See my last comment here: #995

**Comment by zchee** [comment]
@jeffmendoza 
Thanks refer.
I understand the reason for the panic error.

but, Although returns a code that has been deleted, it's state of the processing of docker-machine does not end :(

stopped console result when enable --debug flag
```
DEBU[0055] using auth token: /Users/zchee/.docker/machine/machines/docker-machine-google/gce_token
DEBU[0055] using auth token: /Users/zchee/.docker/machine/machines/docker-machine-google/gce_token
DEBU[0060] using auth token: /Users/zchee/.docker/machine/machines/docker-machine-google/gce_token
DEBU[0061] using auth token: /Users/zchee/.docker/machine/machines/docker-machine-google/gce_token
DEBU[0062] using auth token: /Users/zchee/.docker/machine/machines/docker-machine-google/gce_token
DEBU[0064] using auth token: /Users/zchee/.docker/machine/machines/docker-machine-google/gce_token
```

**Comment by ehazlett** [comment]
All is working for me with both oauth flow and specifying a token.  could you check to make sure the old directory is removed?

**Comment by ehazlett** [comment]
I just checked on Darwin too (I run Linux mostly) and it's working fine there as well with this branch.

**Comment by zchee** [comment]
@ehazlett
I'm works too.
close.
