### ISSUE TITLE
Panic on machine create 

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1068]
(digitalocean, but I don't think it's unique that driver)

What seems to be the relevant bit:

```
  time="2015-04-28T14:09:50-07:00" level="info" msg="Creating SSH key..."
   time="2015-04-28T14:09:52-07:00" level="info" msg="Creating Digital Ocean droplet..."
   panic: runtime error: invalid memory address or nil pointer dereference
   [signal 0xb code=0x1 addr=0x20 pc=0x82fc8]

   goroutine 16 [running]:
   runtime.panic(0x6d5280, 0xb31d84)
   	/usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
   bytes.(*Buffer).ReadFrom(0x208f89ce0, 0x0, 0x0, 0x0, 0x0, 0x0)
   	/usr/src/go/src/pkg/bytes/buffer.go:169 +0x208
   github.com/docker/machine/libmachine/provision.installDockerGeneric(0x2208c51590, 0x208cd9400, 0x0, 0x0)
   	/go/src/github.com/docker/machine/libmachine/provision/utils.go:30 +0xe0
   github.com/docker/machine/libmachine/provision.(*UbuntuProvisioner).Provision(0x208cd9400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x208cb4c40, 0x12, 0x0, ...)
   	/go/src/github.com/docker/machine/libmachine/provision/ubuntu.go:103 +0x288
   github.com/docker/machine/libmachine.(*Host).Create(0x208c37ee0, 0x7fff5fbff973, 0x16, 0x0, 0x0)
   	/go/src/github.com/docker/machine/libmachine/host.go:121 +0x2ba
   github.com/docker/machine/libmachine.(*Machine).Create(0x208cad460, 0x7fff5fbff973, 0x16, 0x208cac5f0, 0xc, 0x208cab300, 0x2208c3a250, 0x208c7a480, 0x0, 0x0, ...)
   	/go/src/github.com/docker/machine/libmachine/machine.go:59 +0x565
   github.com/docker/machine/commands.cmdCreate(0x208c7a480)
   	/go/src/github.com/docker/machine/commands/create.go:89 +0xcae
   github.com/codegangsta/cli.Command.Run(0x77b690, 0x6, 0x0, 0x0, 0x7c2ab0, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
   	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2
   github.com/codegangsta/cli.(*App).Run(0x208c368f0, 0x208c36000, 0xd, 0xd, 0x0, 0x0)
   	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea
   main.main()
   	/go/src/github.com/docker/machine/main.go:73 +0x5a3
```

The offending code seems to be the `buf.ReadFrom` line: 

```go
func installDockerGeneric(p Provisioner) error {
        // install docker - until cloudinit we use ubuntu everywhere so we
        // just install it using the docker repos
        if output, err := p.SSHCommand("if ! type docker; then curl -sSL https://get.docker.com | sh -; fi"); err != nil {
                var buf bytes.Buffer
                if _, err := buf.ReadFrom(output.Stderr); err != nil {
                        return err
                }

                return fmt.Errorf("error installing docker: %s\n", buf.String())
        }

        return nil
}
```

It seems not to like to try and read from `Stderr` when something has gone wrong.  I'm not sure that trying to read from `STDERR` on the command if the right thing to do, really - we might want to just return the error.  If you look at the code for `RunSSHCommandFromDriver`, which `GetSSHCommand` wraps, there are many cases that might cause you to return errors from that function that don't necessarily guarantee getting a `cmd` to read `STDERR` from successfully e.g. we can't establish the SSH hostname. cc @ehazlett @sthulb

**Comment by nathanleclaire** [comment]
I'm not sure if it's related, but I'm getting some (not infrequent) SSH timeouts on create as well:

```
✗ digitalocean: create with supported engine options
   (in test file test/integration/scratch.bats, line 38)
     `[ $status -eq 0 ]' failed
   time="2015-04-28T15:03:48-07:00" level="info" msg="Creating SSH key..."
   time="2015-04-28T15:03:48-07:00" level="info" msg="Creating Digital Ocean droplet..."
   time="2015-04-28T15:05:54-07:00" level="error" msg="Error creating machine: Error getting SSH command: dial tcp 45.55.247.203:22: operation timed out"
   time="2015-04-28T15:05:54-07:00" level="warning" msg="You will want to check the provider to make sure the machine and associated resources were properly removed."
   time="2015-04-28T15:05:54-07:00" level="fatal" msg="Error creating machine"
```

**Comment by ehazlett** [comment]
@nathanleclaire the problem with just returning from an error is that the install script outputs stuff to stderr which appears to be not err.  I believe this is still the case -- I will do a quick test with `curl` to check.

**Comment by nathanleclaire** [comment]
Haven't duped this
