### ISSUE TITLE
Panic running `docker-machine env` without any arguments

### ISSUE THREAD

**Issue by nathanleclaire** [docker/machine#1115]
```console
$ ./docker-machine_darwin-amd64 env
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x47b45]

goroutine 16 [running]:
runtime.panic(0x693e20, 0xad1144)
        /usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/docker/machine/commands.getMachineConfig(0x208c14300, 0x740ff0, 0x0, 0x0)
        /go/src/github.com/docker/machine/commands/commands.go:546 +0xa75
github.com/docker/machine/commands.cmdEnv(0x208c14300)
        /go/src/github.com/docker/machine/commands/env.go:89 +0x8d2
github.com/codegangsta/cli.Command.Run(0x7395f0, 0x3, 0x0, 0x0, 0x835130, 0x44, 0x7b5cf0, 0x1b, 0x0, 0x0, ...)
        /go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2
github.com/codegangsta/cli.(*App).Run(0x208be84e0, 0x208bcc000, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea
main.main()
        /go/src/github.com/docker/machine/main.go:107 +0x5da

goroutine 19 [finalizer wait]:
runtime.park(0x15140, 0xad50e0, 0xad3209)
        /usr/src/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xad50e0, 0xad3209)
        /usr/src/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/src/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
        /usr/src/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32
```

I guess I got something wrong in the "validation"... Investigating

**Comment by nathanleclaire** [comment]
I have a fix in the pipe for this as well
