### ISSUE TITLE
docker-machine ls: "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by radarek** [docker/machine#2280]
```
$ docker-machine ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4adbc2]

goroutine 1 [running]:
github.com/docker/machine/commands.cmdLs(0xc820067e60, 0x0, 0x0)
	/go/src/github.com/docker/machine/commands/ls.go:95 +0xa52
github.com/docker/machine/commands.fatalOnError.func1(0xc820067e60)
	/go/src/github.com/docker/machine/commands/commands.go:44 +0x29
github.com/docker/machine/cli.Command.Run(0x959f80, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x961ca0, 0xd, 0x0, ...)
	/go/src/github.com/docker/machine/cli/command.go:137 +0x1055
github.com/docker/machine/cli.(*App).Run(0xc820067c20, 0xc82000a1a0, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/machine/cli/app.go:175 +0xfd6
main.main()
	/go/src/github.com/docker/machine/cmd/machine.go:144 +0xcc3

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).execServer(0xc8200e0880, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:194 +0xc86
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).Serve(0xc8200e0880, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:211 +0x2d
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func1(0xc8200e0880)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:58 +0x25
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:63 +0xcf

goroutine 9 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0xc82007e580, 0xc820012660, 0xc8200126c0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x37d
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x8e

goroutine 10 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0xc82007e600, 0xc820012720, 0xc820012780)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x37d
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x8e

goroutine 11 [syscall]:
syscall.Syscall(0x0, 0x5, 0xc820100000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x5, 0xc820100000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x5, 0xc820100000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc820026170, 0xc820100000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:211 +0x53
os.(*File).Read(0xc820026170, 0xc820100000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0xc82007e600, 0x0)
	/usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0xc82007e600, 0xc8200127e0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x25
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x81

goroutine 12 [syscall]:
syscall.Syscall(0x0, 0x3, 0xc8200ef010, 0xff0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x3, 0xc8200ef010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x3, 0xc8200ef010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc820026160, 0xc8200ef010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:211 +0x53
os.(*File).Read(0xc820026160, 0xc8200ef010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0xc82007e580, 0x0)
	/usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0xc82007e580, 0xc820012840)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x25
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x81

goroutine 13 [IO wait]:
net.runtime_pollWait(0x7f127d6990b0, 0x72, 0xc82000e170)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200427d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200427d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820042770, 0xc82011d000, 0x1000, 0x1000, 0x0, 0x7f127d693050, 0xc82000e170)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026190, 0xc82011d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820012900)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820012900, 0xc8200ed3c0, 0x1, 0x9, 0xa3c3a8, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f127d6991e8, 0xc820012900, 0xc8200ed3c0, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7f127d6991e8, 0xc820012900, 0xc8200ed3c0, 0x1, 0x9, 0xc82007e7f0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x62
encoding/gob.decodeUintReader(0x7f127d6991e8, 0xc820012900, 0xc8200ed3c0, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x92
encoding/gob.(*Decoder).recvMessage(0xc82007e780, 0xc8200dbbc0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x5e
encoding/gob.(*Decoder).decodeTypeSequence(0xc82007e780, 0xa3d200, 0xc82007e780)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc82007e780, 0x7d3420, 0xc8201201b0, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x15d
encoding/gob.(*Decoder).Decode(0xc82007e780, 0x7d3420, 0xc8201201b0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x289
net/rpc.(*gobClientCodec).ReadResponseHeader(0xc8200d7dd0, 0xc8201201b0, 0x0, 0x0)
	/usr/local/go/src/net/rpc/client.go:223 +0x51
net/rpc.(*Client).input(0xc8200129c0)
	/usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
	/usr/local/go/src/net/rpc/client.go:201 +0xd2

goroutine 14 [sleep]:
time.Sleep(0xbebc200)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func2(0xc8200eafa0)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:91 +0x1dc
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:94 +0x38a

goroutine 16 [chan receive]:
github.com/docker/machine/commands.attemptGetHostState(0xc8200123c0, 0xc820013200)
	/go/src/github.com/docker/machine/commands/ls.go:259 +0x115
created by github.com/docker/machine/commands.getHostState
	/go/src/github.com/docker/machine/commands/ls.go:286 +0x6f

goroutine 17 [chan receive]:
net/rpc.(*Client).Call(0xc8200129c0, 0x9bd300, 0x18, 0x7ed820, 0xc0edc8, 0x892f60, 0xc8200edc40, 0x0, 0x0)
	/usr/local/go/src/net/rpc/client.go:315 +0xcd
github.com/docker/machine/libmachine/drivers/rpc.(*InternalClient).Call(0xc8200eaf80, 0x9bd300, 0x18, 0x7ed820, 0xc0edc8, 0x892f60, 0xc8200edc40, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:40 +0xfd
github.com/docker/machine/libmachine/drivers/rpc.(*RpcClientDriver).GetState(0xc8200eafa0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:245 +0xcc
github.com/docker/machine/commands.attemptGetHostState.func1(0xc8200123c0, 0xc8200132c0)
	/go/src/github.com/docker/machine/commands/ls.go:238 +0x6f
created by github.com/docker/machine/commands.attemptGetHostState
	/go/src/github.com/docker/machine/commands/ls.go:244 +0xb9

goroutine 18 [chan send]:
github.com/docker/machine/commands.attemptGetHostState.func2(0xc8200123c0, 0xc820013320)
	/go/src/github.com/docker/machine/commands/ls.go:256 +0x150
created by github.com/docker/machine/commands.attemptGetHostState
	/go/src/github.com/docker/machine/commands/ls.go:257 +0xe8
```

It happens to me when my computer cannot connect to DigitalOcean API:

```
$ docker-machine ssh foobar
Get https://api.digitalocean.com/v2/droplets/8768721: net/http: TLS handshake timeout
```

```
$ docker-machine -v
docker-machine version 0.5.0 (04cfa58)
```

**Comment by jeanlaurent** [comment]
Sounds very very similar to #2252 altough not on DigitalOcean

**Comment by LokiOfNZ** [comment]
Very similar happening to me after trying to start the default instance that Kitematic creates on Windows 7.

**Comment by tiborvass** [comment]
@ngauthier this should be closed :) I believe you have to add in your PR description, one `Fixes #XXX` line per issue your PR fixes.

(I was hitting this same issue)

**Comment by ngauthier** [comment]
Ah, or is it "Closes XXX"? I can never remember 😀

**Comment by tiborvass** [comment]
@ngauthier both work ;) but needs one closing-word per issue number.

**Comment by dgageot** [comment]
Closed with https://github.com/docker/machine/pull/2306

**Comment by vschiavoni** [comment]
The same happens to me on Mac OSX 10.11.2 : 

```
➜  docker git:(master) ✗ docker-machine -v
docker-machine version 0.5.2 ( 0456b9f )
docker git:(master) ✗ docker-machine ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0xa939f]

goroutine 1 [running]:
github.com/docker/machine/commands.cmdLs(0xa80d00, 0xc820034128, 0xa80d70, 0xc8200f6750, 0x0, 0x0)
	/go/src/github.com/docker/machine/commands/ls.go:74 +0x6ff
github.com/docker/machine/commands.fatalOnError.func1(0xc82007dd40)
	/go/src/github.com/docker/machine/commands/commands.go:108 +0x2a8
github.com/docker/machine/vendor/github.com/codegangsta/cli.Command.Run(0x56f0d8, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x576fc0, 0xd, 0x0, ...)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/command.go:137 +0x107e
github.com/docker/machine/vendor/github.com/codegangsta/cli.(*App).Run(0xc82007db00, 0xc82000a380, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/app.go:175 +0xfff
main.main()
	/go/src/github.com/docker/machine/cmd/machine.go:131 +0xb2f

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by hardywu** [comment]
Same issue again on docker-machine v0.6 in Mac OS X 10.11.2
