### ISSUE TITLE
[Windows] Docker-Machine list intermittently fails with : panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AlexChesser** [docker/machine#2392]
If I run `docker-machine ls` I intermittently get the following error messages.
Notice that if I immediately run the command again I receive a successful execution.

```   
PS C:\www> docker-machine ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x4b1d69]

goroutine 1 [running]:
github.com/docker/machine/commands.cmdLs(0xc0820d8240, 0x0, 0x0)
        /go/src/github.com/docker/machine/commands/ls.go:95 +0xa59
github.com/docker/machine/commands.fatalOnError.func1(0xc0820d8240)
        /go/src/github.com/docker/machine/commands/commands.go:44 +0x30
github.com/docker/machine/cli.Command.Run(0x967508, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x96f570, 0xd, 0x0, ...)
        /go/src/github.com/docker/machine/cli/command.go:137 +0x105c
github.com/docker/machine/cli.(*App).Run(0xc0820d8000, 0xc082006680, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/machine/cli/app.go:175 +0xfdd
main.main()
        /go/src/github.com/docker/machine/cmd/machine.go:144 +0xcca

goroutine 6 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).execServer(0xc0820d7b80, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:194 +0xc8d
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).Serve(0xc0820d7b80, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:211 +0x34
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func1(0xc0820d7b80)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:58 +0x2c
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:63 +0xd6

goroutine 8 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0xc08207bc80, 0xc082123b60, 0xc082123bc0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x384
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x95

goroutine 9 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0xc08207bd00, 0xc082123c20, 0xc082123c80)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x384
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x95

goroutine 10 [syscall, locked to thread]:
syscall.Syscall6(0x76e409a0, 0x5, 0xcc, 0xc08212d050, 0xfb0, 0xc082125c7c, 0x0, 0x0, 0x1, 0x0, ...)
        /usr/local/go/src/runtime/syscall_windows.go:139 +0x5c
syscall.ReadFile(0xcc, 0xc08212d050, 0xfb0, 0xfb0, 0xc082125c7c, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_windows.go:283 +0xcc
syscall.Read(0xcc, 0xc08212d050, 0xfb0, 0xfb0, 0x1, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_windows.go:299 +0x7c
os.(*File).read(0xc082026168, 0xc08212d050, 0xfb0, 0xfb0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file_windows.go:300 +0x153
os.(*File).Read(0xc082026168, 0xc08212d050, 0xfb0, 0xfb0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x91
bufio.(*Scanner).Scan(0xc08207bd00, 0xc082123ce0)
        /usr/local/go/src/bufio/scan.go:180 +0x87e
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0xc08207bd00, 0xc082123ce0)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x2c
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x88

goroutine 17 [syscall, locked to thread]:
syscall.Syscall6(0x76e409a0, 0x5, 0xc4, 0xc08212c010, 0xff0, 0xc08215dc7c, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/syscall_windows.go:139 +0x5c
syscall.ReadFile(0xc4, 0xc08212c010, 0xff0, 0xff0, 0xc08215dc7c, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_windows.go:283 +0xcc
syscall.Read(0xc4, 0xc08212c010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_windows.go:299 +0x7c
os.(*File).read(0xc082026158, 0xc08212c010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file_windows.go:300 +0x153
os.(*File).Read(0xc082026158, 0xc08212c010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x91
bufio.(*Scanner).Scan(0xc08207bc80, 0x0)
        /usr/local/go/src/bufio/scan.go:180 +0x87e
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0xc08207bc80, 0xc082156000)
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x2c
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
        /go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x88

goroutine 33 [IO wait]:
net.runtime_pollWait(0x2c11000, 0x72, 0xc082117790)
        /usr/local/go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc0820362f0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082162000, 0xc0820361e0, 0x964660, 0x7, 0xa4b068, 0x220000, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:182 +0x177
net.(*netFD).Read(0xc082036180, 0xc08216c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:463 +0x17e
net.(*conn).Read(0xc082162010, 0xc08216c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xeb
bufio.(*Reader).fill(0xc082164060)
        /usr/local/go/src/bufio/bufio.go:97 +0x1f0
bufio.(*Reader).Read(0xc082164060, 0xc0821460c0, 0x1, 0x9, 0xa4a7c8, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:207 +0x267
io.ReadAtLeast(0x2c11138, 0xc082164060, 0xc0821460c0, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:298 +0xed
io.ReadFull(0x2c11138, 0xc082164060, 0xc0821460c0, 0x1, 0x9, 0xc08214e0f0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:316 +0x69
encoding/gob.decodeUintReader(0x2c11138, 0xc082164060, 0xc0821460c0, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc08214e080, 0xc08202dbc0)
        /usr/local/go/src/encoding/gob/decoder.go:76 +0x65
encoding/gob.(*Decoder).decodeTypeSequence(0xc08214e080, 0xa4b700, 0xc08214e080)
        /usr/local/go/src/encoding/gob/decoder.go:140 +0x4e
encoding/gob.(*Decoder).DecodeValue(0xc08214e080, 0x7e14c0, 0xc08217e000, 0x16, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:208 +0x164
encoding/gob.(*Decoder).Decode(0xc08214e080, 0x7e14c0, 0xc08217e000, 0x0, 0x0)
        /usr/local/go/src/encoding/gob/decoder.go:185 +0x290
net/rpc.(*gobClientCodec).ReadResponseHeader(0xc0821481b0, 0xc08217e000, 0x0, 0x0)
        /usr/local/go/src/net/rpc/client.go:223 +0x58
net/rpc.(*Client).input(0xc082164120)
        /usr/local/go/src/net/rpc/client.go:109 +0xc6
created by net/rpc.NewClientWithCodec
        /usr/local/go/src/net/rpc/client.go:201 +0xd9

goroutine 34 [runnable]:
time.Sleep(0xbebc200)
        /usr/local/go/src/runtime/time.go:59 +0x107
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func2(0xc0821501e0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:91 +0x1e3
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:94 +0x391

goroutine 36 [chan receive]:
github.com/docker/machine/commands.attemptGetHostState(0xc08200c840, 0xc082164720)
        /go/src/github.com/docker/machine/commands/ls.go:260 +0x15f
created by github.com/docker/machine/commands.getHostState
        /go/src/github.com/docker/machine/commands/ls.go:286 +0x76

goroutine 38 [chan receive]:
net/rpc.(*Client).Call(0xc082164120, 0x9b89c0, 0x16, 0x7fb4a0, 0xc1c5b0, 0x7e4880, 0xc0821464a0, 0x0, 0x0)
        /usr/local/go/src/net/rpc/client.go:315 +0xd4
github.com/docker/machine/libmachine/drivers/rpc.(*InternalClient).Call(0xc0821501c0, 0x9b89c0, 0x16, 0x7fb4a0, 0xc1c5b0, 0x7e4880, 0xc0821464a0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:40 +0x104
github.com/docker/machine/libmachine/drivers/rpc.(*RpcClientDriver).rpcStringCall(0xc0821501e0, 0x9b89c0, 0x16, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:148 +0xe7
github.com/docker/machine/libmachine/drivers/rpc.(*RpcClientDriver).GetURL(0xc0821501e0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:193 +0x55
github.com/docker/machine/libmachine/host.(*Host).GetURL(0xc08200c840, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/host/host.go:149 +0x59
github.com/docker/machine/commands.attemptGetHostState.func2(0xc08200c840, 0xc082164840)
        /go/src/github.com/docker/machine/commands/ls.go:247 +0x59
created by github.com/docker/machine/commands.attemptGetHostState
        /go/src/github.com/docker/machine/commands/ls.go:257 +0xef
PS C:\www>  docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   -        virtualbox   Running   tcp://192.168.99.100:2376
```

**Comment by jeanlaurent** [comment]
@AlexChesser  Which version of `docker-machine` are you using ?

It sounds like #2280, but I'm not completely sure.

**Comment by AlexChesser** [comment]
@jeanlaurent it looks like you're right! I'm on `Version: 0.5.0 (04cfa58)`
I have now updated to version Version: 0.5.1 (7e8e38e)

I will close this. Sorry for the issue-spam.
