### ISSUE TITLE
machine create --driver=digitalocean crash

### ISSUE THREAD

**Issue by SvenDowideit** [docker/machine#246]
only happens if you have no droplets - if i have one or more, then the code hangs at `Waiting for SSH..`

**NOTE, this panic makes no sense to me - that line is a `continue`, so I'm rebulding**

```
mini:machine sven$ ./machine --debug create --driver digitalocean --digitalocean-access-token SNIPO dotest  
INFO[0000] Creating SSH key...                          
DEBU[0000] executing: /usr/bin/ssh-keygen ssh-keygen -t rsa -N  -f /Users/sven/.docker/machines/dotest/id_rsa
 
Generating public/private rsa key pair.
Your identification has been saved in /Users/sven/.docker/machines/dotest/id_rsa.
Your public key has been saved in /Users/sven/.docker/machines/dotest/id_rsa.pub.
The key fingerprint is:
d8:45:0a:26:SNIPO:91 sven@mini
The key's randomart image is:
+--[ RSA 2048]----+
|=B+o. =.  .      |
|=...+Oo. o       |
| ..o E+ . .      |
|    . .o .       |
|     .. S        |
|                 |
|                 |
|                 |
|                 |
+-----------------+
INFO[0001] Creating Digital Ocean droplet...            
DEBU[0004] Created droplet ID 3715105, IP address 104SNIPO.97 
INFO[0004] Waiting for SSH...                           
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x19643f]

goroutine 16 [running]:
runtime.panic(0x593220, 0x908844)
        /usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/docker/machine/ssh.WaitForTCP(0x208d77dc0, 0x11, 0x0, 0x0)
        /go/src/github.com/docker/machine/ssh/ssh.go:64 +0x8f
github.com/docker/machine/drivers/digitalocean.(*Driver).Create(0x2089d8700, 0x0, 0x0)
        /go/src/github.com/docker/machine/drivers/digitalocean/digitalocean.go:146 +0x6a9
main.(*Host).Create(0x208a83e00, 0x0, 0x0)
        /go/src/github.com/docker/machine/host.go:201 +0x56
main.(*Store).Create(0x208a90be0, 0x7fff5fbffdac, 0x6, 0x208a90bc0, 0xc, 0x22089dcdf0, 0x208a8a240, 0x2208b7d888, 0x0, 0x0)
        /go/src/github.com/docker/machine/store.go:55 +0x434
main.cmdCreate(0x208a8a240)
        /go/src/github.com/docker/machine/commands.go:191 +0x40b
github.com/codegangsta/cli.Command.Run(0x6140f0, 0x6, 0x0, 0x0, 0x64ba30, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:101 +0xc6f
github.com/codegangsta/cli.(*App).Run(0x208a8a0c0, 0x2089d8000, 0x8, 0x8, 0x0, 0x0)
        /go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:130 +0x953
main.main()
        /go/src/github.com/docker/machine/main.go:36 +0x310

goroutine 19 [finalizer wait]:
runtime.park(0x1e050, 0x90c658, 0x90a909)
        /usr/src/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x90c658, 0x90a909)
        /usr/src/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/src/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
        /usr/src/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 25 [select]:
net.func·019()
        /usr/src/go/src/pkg/net/dnsclient_unix.go:184 +0x2ab
created by net.loadConfig
        /usr/src/go/src/pkg/net/dnsclient_unix.go:212 +0x153
mini:machine sven$ 
```

**Comment by SvenDowideit** [comment]
rebuild, and the crash goes away, YAY.
