### ISSUE TITLE
Unable to start Hyper-v vm (file used by another process)

### ISSUE THREAD

**Issue by dgageot** [docker/machine#2662]
I'm trying to create a new Hyper-v host with:
```
$ docker-machine version
version 0.5.5-dev build 4d65e4f
$ docker-machine create -d hyperv default
```

Sometimes it works and sometimes it doesn't. I get this error message:

```
(default) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile Start-VM -Name de
fault
(default) Starting  VM...
(default) DBG | [stdout =====>] :
(default) DBG | [stderr =====>] : Start-VM : 'default' failed to start.
(default) DBG | Microsoft Emulated IDE Controller (Instance ID 83F8638B-8DCA-4152-9EDA-2CA8B33039B4): Failed to Power on
 with Error
(default) DBG | 'The process cannot access the file because it is being used by another process.'.
(default) DBG | Failed to open attachment 'C:\Users\dgageot\.docker\machine\machines\default\boot2docker.iso'. Erro
r: 'The
(default) DBG | process cannot access the file because it is being used by another process.'.
(default) DBG | 'default' failed to start. (Virtual machine ID 2DF1FC70-16EC-488D-B49B-581554A19E17)
(default) DBG | 'default' Microsoft Emulated IDE Controller (Instance ID 83F8638B-8DCA-4152-9EDA-2CA8B33039B4): Failed t
o Power on
(default) DBG | with Error 'The process cannot access the file because it is being used by another process.' (0x80070020
). (Virtual
(default) DBG | machine ID 2DF1FC70-16EC-488D-B49B-581554A19E17)
(default) DBG | 'default': Failed to open attachment 'C:\Users\dgageot\.docker\machine\machines\default\boot2docker
.iso'. Error:
(default) DBG | 'The process cannot access the file because it is being used by another process.' (0x80070020). (Virtual
 machine ID
(default) DBG | 2DF1FC70-16EC-488D-B49B-581554A19E17)
(default) DBG | At line:1 char:1
(default) DBG | + Start-VM -Name default
(default) DBG | + ~~~~~~~~~~~~~~~~~~~~~~
(default) DBG |     + CategoryInfo          : ResourceBusy: (:) [Start-VM], VirtualizationException
(default) DBG |     + FullyQualifiedErrorId : ObjectInUse,Microsoft.HyperV.PowerShell.Commands.StartVM
```

I tried multiple things to fix the issue:

+ Retrying to start after a delay
+ Retrying many times

With no success. Sometimes it works and sometimes not. The worst part is that when docker-machine fails, if I just type `start-vm default` in the shell, then it works every time...

**Comment by cvstebut** [comment]
I had the same issue and slightly modifying libmachine/mcnutils/utils.g (adding a defer out.Close()) seems to have fixed the issue for me. Please see PR #2666

**Comment by dgageot** [comment]
Fixed with https://github.com/docker/machine/pull/2658

**Comment by ahmad-punch** [comment]
I am facing the same issue:

Docker Engine
v19.03.12

Details:
Docker.Core.HttpBadResponseException:
Unhandled exception: job failed with message: 'DockerDesktopVM' failed to start. (Virtual machine ID 5EDD5C71-7118-4B42-91E2-54EBFE83D605)

'DockerDesktopVM' Synthetic SCSI Controller (Instance ID 889E00A3-B0D4-4EA1-9CE0-2AEB85831074): Failed to Power on with Error 'The process cannot access the file because it is being used by another process.' (0x80070020). (Virtual machine ID 5EDD5C71-7118-4B42-91E2-54EBFE83D605)

'DockerDesktopVM': Attachment 'C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx' failed to open because of error: 'The process cannot access the file because it is being used by another process.' (0x80070020). (Virtual machine ID 5EDD5C71-7118-4B42-91E2-54EBFE83D605)
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<StartHyperVVMAsync>d__11.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
Original stacktrace:
   at Docker.Backend.HyperVInfrastructure.HandleUpdatedJob(CIMConcreteJob updatedJob) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 800
   at Docker.Backend.HyperVInfrastructure.<HandleMaybeAsyncJob>d__37.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 740
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Backend.HyperVInfrastructure.<StartVMAsync>d__29.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 588
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HyperV.<StartAsync>d__7.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperV.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpAPI.HyperVAPIController.<StartAsync>d__8.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\HyperVAPIController.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
