### ISSUE TITLE
creation of swarm host Fails when swarm shall be listening on unix socket

### ISSUE THREAD

**Issue by nfoonf** [docker/machine#3203]
Docker-machine fails with a stack-trace when a swarm manager is created in virtualbox, that also listens on a unix socket:
```
sh bootstrap-vm4.sh 
Running pre-create checks...
Creating machine...
(vm4) Copying /home/groening/.docker/machine/cache/boot2docker.iso to /home/groening/.docker/machine/machines/vm4/boot2docker.iso...
(vm4) Creating VirtualBox VM...
(vm4) Creating SSH key...
(vm4) Starting the VM...
(vm4) Check network to re-create if needed...
(vm4) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Configuring swarm...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/docker/machine/libmachine/provision.configureSwarm(0x7ff83731bc20, 0xc82008c780, 0x1, 0x0, 0x0, 0xc820288ae0, 0x11, 0x1, 0xc820288b00, 0x1a, ...)
	/go/src/github.com/docker/machine/libmachine/provision/configure_swarm.go:34 +0x1a5b
github.com/docker/machine/libmachine/provision.(*Boot2DockerProvisioner).Provision(0xc82008c780, 0x1, 0x0, 0x0, 0xc820288ae0, 0x11, 0x1, 0xc820288b00, 0x1a, 0xc82028c720, ...)
	/go/src/github.com/docker/machine/libmachine/provision/boot2docker.go:254 +0x572
github.com/docker/machine/libmachine.(*Client).performCreate(0xc8202a2500, 0xc820290600, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/libmachine.go:172 +0xa13
github.com/docker/machine/libmachine.(*Client).Create(0xc8202a2500, 0xc820290600, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/libmachine.go:137 +0x578
github.com/docker/machine/commands.cmdCreateInner(0x7ff8372d3490, 0xc820034228, 0x7ff8372d3508, 0xc8202a2500, 0x0, 0x0)
	/go/src/github.com/docker/machine/commands/create.go:216 +0x1c58
github.com/docker/machine/commands.runCommand.func1(0xc82007c5a0)
	/go/src/github.com/docker/machine/commands/commands.go:161 +0x5e2
github.com/docker/machine/vendor/github.com/codegangsta/cli.Command.Run(0x184beb8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x199ac60, 0x10, 0xc8200d4a80, ...)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/command.go:137 +0x107e
github.com/docker/machine/vendor/github.com/codegangsta/cli.(*App).Run(0xc82020dc20, 0xc82000a1e0, 0x1d, 0x1e, 0x0, 0x0)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/app.go:175 +0xfff
github.com/docker/machine/commands.cmdCreateOuter(0x7ff8372d3490, 0xc8200941b8, 0x7ff8372d3508, 0xc8202121e0, 0x0, 0x0)
	/go/src/github.com/docker/machine/commands/create.go:325 +0x62c
github.com/docker/machine/commands.runCommand.func1(0xc82021e000)
	/go/src/github.com/docker/machine/commands/commands.go:161 +0x5e2
github.com/docker/machine/vendor/github.com/codegangsta/cli.Command.Run(0x184beb8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x199ac60, 0x10, 0xc8200d4a80, ...)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/command.go:137 +0x107e
github.com/docker/machine/vendor/github.com/codegangsta/cli.(*App).Run(0xc82020dc20, 0xc82000a1e0, 0x1d, 0x1e, 0x0, 0x0)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/app.go:175 +0xfff
main.main()
	/go/src/github.com/docker/machine/cmd/machine.go:163 +0xcb9

goroutine 17 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [runnable]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0x3, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:296 +0x4a
os.(*file).close(0xc82023c060, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:126 +0x61
os.(*File).Close(0xc820240000, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:118 +0x54
os/exec.(*Cmd).closeDescriptors(0xc82023e000, 0xc820242020, 0x2, 0x2)
	/usr/local/go/src/os/exec/exec.go:241 +0x84
os/exec.(*Cmd).Wait(0xc82023e000, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:390 +0x365
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*Executor).Close(0xc8202122d0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:163 +0x41
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*Plugin).execServer(0xc820212320, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:212 +0x84b
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*Plugin).Serve(0xc820212320, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:221 +0x2d
github.com/docker/machine/libmachine/drivers/rpc.(*DefaultRPCClientDriverFactory).NewRPCClientDriver.func1(0xc820212320)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:130 +0x25
created by github.com/docker/machine/libmachine/drivers/rpc.(*DefaultRPCClientDriverFactory).NewRPCClientDriver
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:135 +0xcf

goroutine 6 [runnable]:
syscall.Syscall6(0x3d, 0x6e01, 0xc82004da9c, 0x0, 0xc8202ea240, 0x0, 0x0, 0x6e01, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.wait4(0x6e01, 0xc82004da9c, 0x0, 0xc8202ea240, 0x90, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:172 +0x72
syscall.Wait4(0x6e01, 0xc82004dae4, 0x0, 0xc8202ea240, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:256 +0x55
os.(*Process).wait(0xc8202b4c00, 0x2, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x105
os.(*Process).Wait(0xc8202b4c00, 0x2, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:45 +0x2d
os/exec.(*Cmd).Wait(0xc82008a500, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:380 +0x211
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*Executor).Close(0xc8202a25f0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:163 +0x41
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*Plugin).execServer(0xc8202a2640, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:212 +0x84b
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*Plugin).Serve(0xc8202a2640, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:221 +0x2d
github.com/docker/machine/libmachine/drivers/rpc.(*DefaultRPCClientDriverFactory).NewRPCClientDriver.func1(0xc8202a2640)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:130 +0x25
created by github.com/docker/machine/libmachine/drivers/rpc.(*DefaultRPCClientDriverFactory).NewRPCClientDriver
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:135 +0xcf

goroutine 7 [runnable]:
syscall.Syscall(0x0, 0x7, 0xc8202af10d, 0xef3, 0x0, 0xef3, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x7, 0xc8202af10d, 0xef3, 0xef3, 0x15, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x7, 0xc8202af10d, 0xef3, 0xef3, 0x15, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc820034250, 0xc8202af10d, 0xef3, 0xef3, 0x80e5b7, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:211 +0x53
os.(*File).Read(0xc820034250, 0xc8202af10d, 0xef3, 0xef3, 0xc81ffe3b0c, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0xc820087500, 0xc8202a6540)
	/usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0xc820087500, 0xc8202a6540)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:171 +0x30
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*Plugin).AttachStream
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:182 +0x5d

goroutine 8 [chan send]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0xc820087580, 0xc8202a65a0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:176 +0x298
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*Plugin).AttachStream
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:182 +0x5d

goroutine 50 [IO wait]:
net.runtime_pollWait(0x7ff837317230, 0x72, 0xc820010180)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202866f0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202866f0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820286690, 0xc8202ec000, 0x1000, 0x1000, 0x0, 0x7ff837312050, 0xc820010180)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820284128, 0xc8202ec000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820290300)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820290300, 0xc82028c4e0, 0x1, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7ff837317428, 0xc820290300, 0xc82028c4e0, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7ff837317428, 0xc820290300, 0xc82028c4e0, 0x1, 0x9, 0xc8202d00f0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x62
encoding/gob.decodeUintReader(0x7ff837317428, 0xc820290300, 0xc82028c4e0, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x92
encoding/gob.(*Decoder).recvMessage(0xc8202d0080, 0xc82062fbd0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x5e
encoding/gob.(*Decoder).decodeTypeSequence(0xc8202d0080, 0x1cb2b00, 0xc8202d0080)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc8202d0080, 0x109d780, 0xc8202807e0, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x15d
encoding/gob.(*Decoder).Decode(0xc8202d0080, 0x109d780, 0xc8202807e0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x289
net/rpc.(*gobClientCodec).ReadResponseHeader(0xc820280750, 0xc8202807e0, 0x0, 0x0)
	/usr/local/go/src/net/rpc/client.go:223 +0x51
net/rpc.(*Client).input(0xc8202903c0)
	/usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
	/usr/local/go/src/net/rpc/client.go:201 +0xd2

```

this behavior happens if we supply the option **--swarm-host unix:///var/run/swarm.sock** in the creation config:

```
#!/bin/sh
export base=/home/groening/daten/swarm-bootstrap
export MACHINE_TLS_CA_CERT=${base}/ca/ca.pem
export MACHINE_TLS_CA_KEY=${base}/ca/ca-key.pem
export MACHINE_TLS_CLIENT_CERT=${base}/ca/cert.pem
export MACHINE_TLS_CLIENT_KEY=${base}/ca/key.pem


docker-machine \
  --tls-ca-cert $MACHINE_TLS_CA_CERT \
  --tls-ca-key $MACHINE_TLS_CA_KEY \
  --tls-client-cert $MACHINE_TLS_CLIENT_CERT \
  --tls-client-key $MACHINE_TLS_CLIENT_KEY \
  create \
  --driver virtualbox \
  --engine-opt cluster-store=consul://vm1:8500 \
  --engine-label de.silpion.vagrant.swarm=master \
  --engine-label de.silpion.vagrant.swarm=agent \
  --swarm \
  --swarm-image swarm:1.1.3 \
  --swarm-master \
  --swarm-host tcp://0.0.0.0:3376 \
  --swarm-discovery consul://vm4:8500 \
  --swarm-strategy spread \
  vm4
```

**Comment by nathanleclaire** [comment]
Is this with Machine 0.6.0?  Master?

**Comment by nfoonf** [comment]
Sorry, I forgot this info:

$ docker-machine --version
docker-machine version 0.6.0, build e27fb87
