### ISSUE TITLE
Panic when docker-machine ls

### ISSUE THREAD

**Issue by labkode** [docker/machine#3437]
```
➜  govocitos git:(master) docker-machine ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xad9d2]

goroutine 1 [running]:
github.com/docker/machine/commands.cmdLs(0xc8200fc360, 0x0, 0x0)
	/go/src/github.com/docker/machine/commands/ls.go:95 +0xa52
github.com/docker/machine/commands.fatalOnError.func1(0xc8200fc360)
	/go/src/github.com/docker/machine/commands/commands.go:44 +0x29
github.com/docker/machine/cli.Command.Run(0x5563a0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55e030, 0xd, 0x0, ...)
	/go/src/github.com/docker/machine/cli/command.go:137 +0x1055
github.com/docker/machine/cli.(*App).Run(0xc8200fc120, 0xc82000a1e0, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/machine/cli/app.go:175 +0xfd6
main.main()
	/go/src/github.com/docker/machine/cmd/machine.go:144 +0xcc3

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).execServer(0xc8200fe800, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:194 +0xc86
github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).Serve(0xc8200fe800, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:211 +0x2d
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func1(0xc8200fe800)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:58 +0x25
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:63 +0xcf

goroutine 17 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0xc82012c000, 0xc820138060, 0xc8201380c0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x37d
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x8e

goroutine 18 [select]:
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream(0xc82012c080, 0xc820138120, 0xc820138180)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:154 +0x37d
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.(*LocalBinaryPlugin).AttachStream
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:170 +0x8e

goroutine 19 [syscall]:
syscall.Syscall(0x3, 0x5, 0xc82012b050, 0xfb0, 0x50, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x5, 0xc82012b050, 0xfb0, 0xfb0, 0x50, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x5, 0xc82012b050, 0xfb0, 0xfb0, 0x50, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc820124010, 0xc82012b050, 0xfb0, 0xfb0, 0x300d07, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0xc820124010, 0xc82012b050, 0xfb0, 0xfb0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0xc82012c080, 0xc8201381e0)
	/usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0xc82012c080, 0xc8201381e0)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x25
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x81

goroutine 9 [syscall]:
syscall.Syscall(0x3, 0x3, 0xc82012a010, 0xff0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x3, 0xc82012a010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x3, 0xc82012a010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc820124000, 0xc82012a010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0xc820124000, 0xc82012a010, 0xff0, 0xff0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Scanner).Scan(0xc82012c000, 0x0)
	/usr/local/go/src/bufio/scan.go:180 +0x877
github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream.func1(0xc82012c000, 0xc82001a480)
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:149 +0x25
created by github.com/docker/machine/libmachine/drivers/plugin/localbinary.stream
	/go/src/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go:152 +0x81

goroutine 33 [IO wait]:
net.runtime_pollWait(0xacf000, 0x72, 0xc8200121a0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820148060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820148060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820148000, 0xc820158000, 0x1000, 0x1000, 0x0, 0xa4e050, 0xc8200121a0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82014e000, 0xc820158000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820150060)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820150060, 0xc82013a040, 0x1, 0x9, 0x6377c0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0xacf138, 0xc820150060, 0xc82013a040, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0xacf138, 0xc820150060, 0xc82013a040, 0x1, 0x9, 0xc8201460f0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x62
encoding/gob.decodeUintReader(0xacf138, 0xc820150060, 0xc82013a040, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x92
encoding/gob.(*Decoder).recvMessage(0xc820146080, 0xc8200f7bc0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x5e
encoding/gob.(*Decoder).decodeTypeSequence(0xc820146080, 0x638600, 0xc820146080)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc820146080, 0x3cfdc0, 0xc82017c000, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x15d
encoding/gob.(*Decoder).Decode(0xc820146080, 0x3cfdc0, 0xc82017c000, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x289
net/rpc.(*gobClientCodec).ReadResponseHeader(0xc8201441b0, 0xc82017c000, 0x0, 0x0)
	/usr/local/go/src/net/rpc/client.go:223 +0x51
net/rpc.(*Client).input(0xc820150120)
	/usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
	/usr/local/go/src/net/rpc/client.go:201 +0xd2

goroutine 34 [sleep]:
time.Sleep(0xbebc200)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver.func2(0xc82014a100)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:91 +0x1dc
created by github.com/docker/machine/libmachine/drivers/rpc.NewRpcClientDriver
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:94 +0x38a

goroutine 50 [chan receive]:
github.com/docker/machine/commands.attemptGetHostState(0xc82001a300, 0xc8201a2360)
	/go/src/github.com/docker/machine/commands/ls.go:260 +0x158
created by github.com/docker/machine/commands.getHostState
	/go/src/github.com/docker/machine/commands/ls.go:286 +0x6f

goroutine 36 [chan receive]:
net/rpc.(*Client).Call(0xc820150120, 0x5a6020, 0x16, 0x3e9a40, 0x808728, 0x3d3480, 0xc82013a3a0, 0x0, 0x0)
	/usr/local/go/src/net/rpc/client.go:315 +0xcd
github.com/docker/machine/libmachine/drivers/rpc.(*InternalClient).Call(0xc82014a0e0, 0x5a6020, 0x16, 0x3e9a40, 0x808728, 0x3d3480, 0xc82013a3a0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:40 +0xfd
github.com/docker/machine/libmachine/drivers/rpc.(*RpcClientDriver).rpcStringCall(0xc82014a100, 0x5a6020, 0x16, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:148 +0xe0
github.com/docker/machine/libmachine/drivers/rpc.(*RpcClientDriver).GetURL(0xc82014a100, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/client_driver.go:193 +0x4e
github.com/docker/machine/libmachine/host.(*Host).GetURL(0xc82001a300, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/host/host.go:149 +0x52
github.com/docker/machine/commands.attemptGetHostState.func2(0xc82001a300, 0xc820150660)
	/go/src/github.com/docker/machine/commands/ls.go:247 +0x52
created by github.com/docker/machine/commands.attemptGetHostState
	/go/src/github.com/docker/machine/commands/ls.go:257 +0xe8
```

**Comment by fsoppelsa** [comment]
Is this a compiled version from master? And which one?
