### ISSUE TITLE
Azure - docker attach causes error: 'invalid memory address or nil pointer dereference'

### ISSUE THREAD

**Issue by shuoyenl** [docker/machine#3450]
Hi,
I run into a runtime error of 'invalid memory address or nil pointer dereference' when trying to attach to a container (simply with the microsoft/iis image on the Docker Hub) on an Azure Windows Server 2016 instance. The docker version is 1.12.0-dev. Any suggestions? Thanks!

Below shows the full message:
docker : panic: runtime error: invalid memory address or nil pointer dereference
At line:1 char:1
+ docker attach be371471267a
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: runtime ...ter dereference:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[signal 
0xc0000005
 code=
0x0
 addr=
0x28
 pc=
0x4a1d06
]
goroutine 
14
 [
running
]:
github.com/Sirupsen/logrus.(*Logger).Debugf
(
0x0
, 
0xb97e00
, 
0x4e
, 
0xc082291b88
, 
0x3
, 
0x3
)
	
/go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/logger.go
:
74
 +
0x26
github.com/docker/docker/pkg/term/windows.readInputEvents
(
0x76c
, 
0x8000
, 
0x0
, 
0x0
, 
0x0
, 
0x0
, 
0x0
)
	
/go/src/github.com/docker/docker/pkg/term/windows/ansi_reader.go
:
115
 +
0x262
github.com/docker/docker/pkg/term/windows.(*ansiReader).Read
(
0xc08218cdc0
, 
0xc082292000
, 
0x8000
, 
0x8000
, 
0x8000
, 
0x0
, 
0x0
)
	
/go/src/github.com/docker/docker/pkg/term/windows/ansi_reader.go
:
74
 +
0x47b
io.copyBuffer
(
0xf99110
, 
0xc08226b1a0
, 
0xf99740
, 
0xc08218cdc0
, 
0xc082292000
, 
0x8000
, 
0x8000
, 
0x0
, 
0x0
, 
0x0
)
	
/usr/local/go1.5.3/src/io/io.go
:
381
 +
0x24e
io.Copy
(
0xf99110
, 
0xc08226b1a0
, 
0xf99740
, 
0xc08218cdc0
, 
0xc08218cdc0
, 
0x0
, 
0x0
)
	
/usr/local/go1.5.3/src/io/io.go
:351 +0x6b
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection.func3(0xf98d28, 0xc08218cdc0, 0xc08226b1e0, 0xc08227cc01, 0xc08227cc10, 0xc08216cf80, 
0xc08226d2c0)
	/go/src/github.com/docker/docker/api/client/hijack.go:55 +0xdd
created by github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection
	/go/src/github.com/docker/docker/api/client/hijack.go:70 +0x24c
goroutine 1 [select]:
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection(0xc08216cf80, 0xf988e0, 0xc082003540, 0xc082002201, 0xf98d28, 0xc08218cdc0, 0xf94390, 
0xc082022010, 0xf94390, 0xc082022018, ...)
	/go/src/github.com/docker/docker/api/client/hijack.go:72 +0x704
github.com/docker/docker/api/client.(*DockerCli).CmdAttach(0xc08216cf80, 0xc082005ee0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/attach.go:94 +0xf35
reflect.callMethod(0xc082269170, 0xc082115c88)
	/usr/local/go1.5.3/src/reflect/value.go:628 +0x203
reflect.methodValueCall(0xc082005ee0, 0x1, 0x1, 0x1, 0xc082269170, 0x0, 0x0, 0xc082269170, 0x0, 0x46631b, ...)
	/usr/local/go1.5.3/src/reflect/asm_amd64.s:29 +0x3d
github.com/docker/docker/cli.(*Cli).Run(0xc082231e60, 0xc082005ed0, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x38a
main.main()
	/go/src/github.com/docker/docker/cmd/docker/docker.go:58 +0x384
goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go1.5.3/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
	/usr/local/go1.5.3/src/os/signal/signal_unix.go:28 +0x3e
goroutine 12 [runnable]:
github.com/docker/docker/pkg/term.restoreAtInterrupt.func1(0xc08226d200, 0x76c, 0xc08226b200)
	/go/src/github.com/docker/docker/pkg/term/term_windows.go:296
created by github.com/docker/docker/pkg/term.restoreAtInterrupt
	/go/src/github.com/docker/docker/pkg/term/term_windows.go:300 +0xee
goroutine 13 [runnable]:
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection.func2(0xc08226d201, 0xf94390, 0xc082022010, 0xc08227cc00, 0xc08226b1e0, 0xf98d28, 0xc08218cdc0, 
0xc08227cc10, 0xc08216cf80, 0xf94390, ...)
	/go/src/github.com/docker/docker/api/client/hijack.go:32
created by github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection
	/go/src/github.com/docker/docker/api/client/hijack.go:49 +0x7a1
goroutine 8 [syscall, locked to thread]:
syscall.Syscall6(0x7ffa3bae6f90, 0x5, 0x1c4, 0xc082275f54, 0xc082275f58, 0xc082275f60, 0xffffffff, 0x0, 0xc082275f78, 0x1, ...)
	/usr/local/go1.5.3/src/runtime/syscall_windows.go:139 +0x5c
github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x1c4, 0xc082275f54, 0xc082275f58, 0xc082275f60, 0xffffffff, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/zsyscall.go:72 +0x99
github.com/Microsoft/go-winio.ioCompletionProcessor(0x1c4)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:127 +0x7c
created by github.com/Microsoft/go-winio.initIo
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:55 +0xb3
goroutine 9 [chan receive]:
github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc08218dcc0, 0xc082269530, 0x0, 0x0, 0x0, 0xc000000000, 0xf90050, 0xc082260a60, 0x412d49, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:165 +0x176
github.com/Microsoft/go-winio.(*win32File).Read(0xc08218dcc0, 0xc082267000, 0x1000, 0x1000, 0x8d16c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:188 +0x15f
github.com/Microsoft/go-winio.(*win32MessageBytePipe).Read(0xc08226a4a0, 0xc082267000, 0x1000, 0x1000, 0x404fe5, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/pipe.go:114 +0x94
net/http.noteEOFReader.Read(0xf990c0, 0xc08226a4a0, 0xc08200ecb8, 0xc082267000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go1.5.3/src/net/http/transport.go:1370 +0x6e
net/http.(*noteEOFReader).Read(0xc08226a4c0, 0xc082267000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd7
bufio.(*Reader).fill(0xc08226cd80)
	/usr/local/go1.5.3/src/bufio/bufio.go:97 +0x1f0
b
ufio.(*Reader).Peek(0xc08226cd80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go1.5.3/src/bufio/bufio.go:132 +0xd3
net/http.(*persistConn).readLoop(0xc08200ec60)
	/usr/local/go1.5.3/src/net/http/transport.go:876 +0xfe
created by net/http.(*Transport).dialConn
	/usr/local/go1.5.3/src/net/http/transport.go:685 +0xc7f
goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc08200ec60)
	/usr/local/go1.5.3/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
	/usr/local/go1.5.3/src/net/http/transport.go:686 +0xca4

**Comment by cfstras** [comment]
Have a look at https://github.com/docker/docker/pull/22951 -- it should be fixed with 1.12.

**Comment by ahmetalpbalkan** [comment]
@nathanleclaire please close
