### ISSUE TITLE
Error creating machine: Error detecting OS: OS type not recognized

### ISSUE THREAD

**Issue by SplicePHP** [docker/machine#3586]
Hi,
I am unable to create default on a fresh install of windows 64.
Extensive google searches turned up nothing helpful on the topic.

**Hardware specs:**
Asus H170-Plus D3, Intel G4400 (3.3 dual core), 14 gig 1333 ddr3, ATI 6800 Eyefinity.
( Internet over Ethernet cable with no proxies. )

**Software:**
Windows 10 pro 64bit, fresh install and updated drivers.
Docker for Windows beta. [ Docker starts successfully ]
Docker Toolbox.
Kitematic
Cygwin with OpenSSH.
Hyper-V enabled.
( Currently no anti-virus or firewall installed )

**Powershell output**
```
PS C:\Users\USERNAME> docker-machine create --driver hyperv default
Running pre-create checks...
Creating machine...
(default) Copying C:\Users\USERNAME\.docker\machine\cache\boot2docker.iso to C:\Users\USERNAME\.docker\machine\machines\default\boot2docker.iso...
(default) Creating SSH key...
(default) Creating VM...
(default) Using switch "DockerNAT"
(default) Creating VHD
(default) Starting VM...
(default) Waiting for host to start...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Error creating machine: Error detecting OS: OS type not recognized
PS C:\Users\USERNAME>

```

**Footnote**
The first time docker runs I get this error:
```
Docker daemon is not running
   at Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Core.Backend.BackendClient.Start(Settings settings)
   at Docker.Actions.DoStart(Settings settings, Boolean showWelcomeWindow)
   at Docker.Actions.<ResetToDefault>b__18_0()
   at Docker.Core.TaskQueue.<.ctor>b__16_0()
```
After a reboot the error goes away and docker starts without showing any errors.

Thanks.

**Comment by getglad** [comment]
Were you able to fix? I have same error Win Server 2012

**Comment by SplicePHP** [comment]
Nope, I decided to trash windows and install Linux as my primary operating system and haven't looked back. Good luck getting it working.

**Comment by Jkaveri** [comment]
@SplicePHP You need to follow [this blog](https://blogs.technet.microsoft.com/canitpro/2014/03/10/step-by-step-enabling-hyper-v-for-use-on-windows-8-1/) to enable external switch (e.g: Virtual Switch (Main)) and then your command will look like that: `docker-machine create --driver hyperv --hyperv-virtual-switch "Virtual Switch (Main)" default`

Hope it works.
Thanks.

**Comment by kimcu2015** [comment]
@Jkaveri 
It works. Thanks!!

For more information, the default Virtual Switch of Docker named DockerNat. The main purpose of this step is to configure the external of docker-machine by using real wifi device, I think.

**Comment by JustinJKlein** [comment]
I ran into the same issue as well and this got me running too. Thanks! Docker on WIN 10! 

**When selecting external network connection type make sure that you point to Intel gigabit network connection. Mine defaulted to my network adaptor and caused some crashes when calling out to the internet before I found it.

**Comment by MatrixManAtYrService** [comment]
I ran into this error on Windows Server 2016.  The `--hyperv-virtual-switch` command did not fix it for me.  I launched hyperv manager and learned that the default switch name was just `nat` but that didn't help.

**Comment by Ravi-Macha** [comment]
I am facing same issue,,, 
1.docker-machine create --driver hyperv default
    Error with pre-create check: "no vswitch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/"

**Comment by igoralves1** [comment]
windows crap

**Comment by LawnboyMax** [comment]
I fixed this issue by connecting the virtual switch through an Ethernet connection in Hyper-V Manager. Connecting through wireless was causing the `OS type not recognized` error. The wireless signal goes through VPN so maybe this was causing the issue.

**Comment by Manish22332** [comment]
How long does it take to create the machine? Its stuck at "waiting for host to start"

**Comment by drungrin** [comment]
1. Install git to get git bash
2. run the commans from git bash

Unbelievable, but this is the solution

**Comment by timothy2005** [comment]
I have also encounter this issue,
I guess the root cause is: I did not stop minikube correctly.
Because I met following error when I tried to stop it
**error stopping host: minikube: exit status 1**
then I stopped it by running: **minikube** ssh and **sudo poweroff**
then when I tried to start minikube, I met **OS type not recognized**
I fixed it like below: 
**Turn off minikube vm in hyper-v** and **start minikube again**

**Comment by chanjamin** [comment]
> @Jkaveri
> It works. Thanks!!
> 
> For more information, the default Virtual Switch of Docker named DockerNat.
> The main purpose of this step is to configure the external of docker-machine by using real wifi device, I think.
> And the root cause of this error is docker-machine cannot connect with boot2docker.
> 
> ![image](https://cloud.githubusercontent.com/assets/12949191/17455606/469b25b4-5be7-11e6-8c61-cff6413de4bd.png)

is that extranl device is wifi  device causing this promble?

**Comment by chanjamin** [comment]
> @Jkaveri
> It works. Thanks!!
> 
> For more information, the default Virtual Switch of Docker named DockerNat.
> The main purpose of this step is to configure the external of docker-machine by using real wifi device, I think.
> And the root cause of this error is docker-machine cannot connect with boot2docker.
> 
> ![image](https://cloud.githubusercontent.com/assets/12949191/17455606/469b25b4-5be7-11e6-8c61-cff6413de4bd.png)

@kimcu-on-thenet 
figure it out. some wifi device seems not so compatible with docker-machine.i change external switch to even iphone enthernet provider and everything works fine.
