### ISSUE TITLE
Docker for Windows on an Azure Windows 10 Virtual Machine.

### ISSUE THREAD

**Issue by kiwiingenuity** [docker/machine#4104]
I'm attempting to get started on learning how to use Docker.

I installed Docker for Windows onto my "Azure Windows 10 virtual machine".  The installation succeeded.
If I select "Switch to Windows container" all appears to be well.
However if I "Switch to Linux Containers" then an error message appears which states
An error occurred
The operation has timed out.
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

If I look at the settings -> Shared Drives none of my drives are selected.  I attempted to assign drive C but each time I click apply the screen refreshes and again no shared drive is selected?

Is there a known fix to this issue?

**Comment by kiwiingenuity** [comment]
This is now working as expected.
