### ISSUE TITLE
"docker-machine.exe -D create" is failing because the machine already exists (Win 10)

### ISSUE THREAD

**Issue by jcollum-cambia** [docker/machine#4209]
```
Command failed: C:\Program Files\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default,
Docker Machine Version: 0.12.2,
 build 9371605,
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,
Launching plugin server for driver virtualbox,
Plugin server listening at address 127.0.0.1:59718,
() Calling .GetVersion,
Using API Version 1,
() Calling .SetConfigRaw,
() Calling .GetMachineName,
(flag-lookup) Calling .GetMachineName,
(flag-lookup) Calling .DriverName,
(flag-lookup) Calling .GetCreateFlags,
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,
Launching plugin server for driver virtualbox,
Plugin server listening at address 127.0.0.1:59722,
() Calling .GetVersion,
Using API Version 1,
() Calling .SetConfigRaw,
() Calling .GetMachineName,
(default) Calling .GetMachineName,
(default) Calling .DriverName,
Host already exists: "default",
```

Did it not check to see if the machine already exists before creating it? I've tried "Delete VM & Retry Setup" to no avail. I suppose I'll take a shot at deleting it via command line.

```
$ & 'C:\Program Files\Docker Toolbox\docker-machine.exe' --version
docker-machine.exe version 0.12.2, build 9371605
```

**Comment by jcollum-cambia** [comment]
Well that's puzzling: 

```
& 'C:\Program Files\Docker Toolbox\docker-machine.exe' kill default
open C:\Users\r631947\.docker\machine\machines\default\config.json: The system cannot find the file specified.
```

Did it fail to create the default config.json during install?

**Comment by jcollum-cambia** [comment]
OK I read issue https://github.com/docker/kitematic/issues/1271 and the suggestion was to rm the machine. But that fails: 

```
$ docker-machine rm default
About to remove default
WARNING: This action will delete both local reference and remote instance.
Are you sure? (y/n): y
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7addf3]

goroutine 1 [running]:
github.com/docker/machine/libmachine/host.MigrateHostV2ToHostV3(0xc042149400, 0xc04214e480, 0x18, 0x218, 0x14254f4, 0x1, 0x0)
        /go/src/github.com/docker/machine/libmachine/host/migrate_v2_v3.go:26 +0x1d3
github.com/docker/machine/libmachine/host.MigrateHost(0xc042147620, 0xc04214e480, 0x18, 0x218, 0x218, 0x0, 0x0, 0x29)
        /go/src/github.com/docker/machine/libmachine/host/migrate.go:109 +0x85a
github.com/docker/machine/libmachine/persist.Filestore.loadConfig(0xc0420036e0, 0x20, 0xc042145c50, 0x26, 0xc042145c50, 0x26, 0xc042147620, 0x29, 0x79)
        /go/src/github.com/docker/machine/libmachine/persist/filestore.go:122 +0x15f
github.com/docker/machine/libmachine/persist.Filestore.Load(0xc0420036e0, 0x20, 0xc042145c50, 0x26, 0xc042145c50, 0x26, 0xc042038186, 0x7, 0x0, 0x0, ...)
        /go/src/github.com/docker/machine/libmachine/persist/filestore.go:158 +0x174
github.com/docker/machine/libmachine.(*Client).Load(0xc0420119a0, 0xc042038186, 0x7, 0x0, 0xc04200de10, 0xd)
        /go/src/github.com/docker/machine/libmachine/libmachine.go:92 +0x79
github.com/docker/machine/commands.removeRemoteMachine(0xc042038186, 0x7, 0x1d69240, 0xc0420119a0, 0x1, 0xc042003da0)
        /go/src/github.com/docker/machine/commands/rm.go:68 +0x50
github.com/docker/machine/commands.cmdRm(0x1d69940, 0xc0420040c8, 0x1d69240, 0xc0420119a0, 0x1, 0x539bb7)
        /go/src/github.com/docker/machine/commands/rm.go:32 +0x3a7
github.com/docker/machine/commands.runCommand.func1(0xc042200480)
        /go/src/github.com/docker/machine/commands/commands.go:163 +0x4bb
github.com/docker/machine/vendor/github.com/codegangsta/cli.Command.Run(0x14256d1, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1436a42, 0x10, 0x147320d, ...)
        /go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/command.go:137 +0x891
github.com/docker/machine/vendor/github.com/codegangsta/cli.(*App).Run(0xc042200120, 0xc04203bf50, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/app.go:175 +0x8ef
main.main()
        /go/src/github.com/docker/machine/cmd/machine.go:163 +0xacb
$
```

**Comment by jcollum-cambia** [comment]
Related 

https://github.com/docker/machine/issues/2392
https://github.com/docker/machine/issues/2280

**Comment by shin-** [comment]
Have you tried creating it with a different name? Does that fail as well?

**Comment by jcollum-cambia** [comment]
I don't think I can get back to this setup easily. I'm on Windows 10 so I think I'd have to remove HyperV to get back to there. Not interested in investing the time; using Docker for Windows now, not Docker Machine (I believe those two are different).
