### ISSUE TITLE
docker-machine unable to use

### ISSUE THREAD

**Issue by mozinrat** [docker/machine#4267]
```
RohitVermasMBP:~ rohitverma$ docker-machine ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x139e88c]

goroutine 1 [running]:
github.com/docker/machine/libmachine/host.MigrateHostV2ToHostV3(0xc42013bb00, 0xc42020a240, 0x3, 0x203, 0x1fe32f4, 0x1, 0x0)
	/go/src/github.com/docker/machine/libmachine/host/migrate_v2_v3.go:26 +0x1cc
github.com/docker/machine/libmachine/host.MigrateHost(0xc420064e40, 0xc42020a240, 0x3, 0x203, 0x203, 0x0, 0x0, 0x2a)
	/go/src/github.com/docker/machine/libmachine/host/migrate.go:109 +0x853
github.com/docker/machine/libmachine/persist.Filestore.loadConfig(0xc42010b9b0, 0x21, 0xc42010ba40, 0x27, 0xc42010ba40, 0x27, 0xc420064e40, 0x2a, 0x30)
	/go/src/github.com/docker/machine/libmachine/persist/filestore.go:122 +0x158
github.com/docker/machine/libmachine/persist.Filestore.Load(0xc42010b9b0, 0x21, 0xc42010ba40, 0x27, 0xc42010ba40, 0x27, 0xc42013b92b, 0x7, 0x1007685, 0x28e9b1ee, ...)
	/go/src/github.com/docker/machine/libmachine/persist/filestore.go:158 +0x16d
github.com/docker/machine/libmachine.(*Client).Load(0xc4200157c0, 0xc42013b92b, 0x7, 0x0, 0xc42010bb60, 0x0)
	/go/src/github.com/docker/machine/libmachine/libmachine.go:92 +0x72
github.com/docker/machine/libmachine/persist.LoadHosts(0x2e9c120, 0xc4200157c0, 0xc420155190, 0x1, 0x1, 0x0, 0x1f4faa0, 0x0, 0x2e9c120)
	/go/src/github.com/docker/machine/libmachine/persist/store.go:29 +0xff
github.com/docker/machine/libmachine/persist.LoadAllHosts(0x2e9c120, 0xc4200157c0, 0xc4200157c0, 0x2e9c120, 0xc4200157c0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/persist/store.go:45 +0xbb
github.com/docker/machine/commands.cmdLs(0x2926e40, 0xc42000c200, 0x2926740, 0xc4200157c0, 0x0, 0x0)
	/go/src/github.com/docker/machine/commands/ls.go:83 +0x12b
github.com/docker/machine/commands.runCommand.func1(0xc420208d80)
	/go/src/github.com/docker/machine/commands/commands.go:163 +0x4b4
github.com/docker/machine/vendor/github.com/codegangsta/cli.Command.Run(0x1fe34c0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1feeabc, 0xd, 0x0, ...)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/command.go:137 +0x88a
github.com/docker/machine/vendor/github.com/codegangsta/cli.(*App).Run(0xc420208a20, 0xc42000a240, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/app.go:175 +0x8e8
main.main()
	/go/src/github.com/docker/machine/cmd/machine.go:163 +0xac4
RohitVermasMBP:~ rohitverma$ 

```

**Comment by shin-** [comment]
Can you run the following command and share the output here? `find ~/.docker/machine/machines/ -name "config.json" | xargs cat | grep -E 'MachineName|ConfigVersion'`
