### ISSUE TITLE
Error using vmwarevsphere driver with distributed port groups

### ISSUE THREAD

**Issue by keaneokelley** [docker/machine#4433]
I am able to deploy Docker machines just fine to a VMware vCenter server. However, when I specify a distributed port group with the `--vmwarevsphere-network` flag, I get the following error when attaching the network interface:
```go
Docker Machine Version:  0.14.0, build 89b8332
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver vmwarevsphere
Plugin server listening at address 127.0.0.1:37307
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver vmwarevsphere
Plugin server listening at address 127.0.0.1:37347
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(redbot-test3) Calling .GetMachineName
(redbot-test3) Calling .DriverName
(redbot-test3) Calling .GetCreateFlags
(redbot-test3) Calling .SetConfigFromFlags
Running pre-create checks...
(redbot-test3) Calling .PreCreateCheck
(redbot-test3) DBG | Connecting to vSphere for pre-create checks...
(redbot-test3) Calling .GetConfigRaw
Creating machine...
(redbot-test3) Calling .Create
(redbot-test3) DBG | local Boot2Docker ISO version:  v17.12.1-ce
(redbot-test3) Copying /home/user/.docker/machine/cache/boot2docker.iso to /home/user/.docker/machine/machines/redbot-test3/boot2docker.iso...
(redbot-test3) Generating SSH Keypair...
(redbot-test3) Creating VM...
(redbot-test3) Uploading Boot2docker ISO ...
Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference
goroutine 56 [running]:
runtime/debug.Stack(0xc4203d8858, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/docker/machine/libmachine/drivers/rpc.(*StandardStack).Stack(0x1edb5a0, 0x121bba0, 0x1eac410, 0x1e78720)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:23 +0x22
github.com/docker/machine/libmachine/drivers/rpc.trapPanic(0xc420339ae0)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:129 +0xa5
panic(0x121bba0, 0x1eac410)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/docker/machine/vendor/github.com/vmware/govmomi/object.DistributedVirtualPortgroup.EthernetCardBackingInfo(0xc420096000, 0xc420370580, 0x1b, 0xc420370640, 0x11, 0xc4204b2500, 0x19, 0x1e7dea0, 0xc4203d8840, 0x30, ...)
	/go/src/github.com/docker/machine/vendor/github.com/vmware/govmomi/object/distributed_virtual_portgroup.go:52 +0x24f
github.com/docker/machine/vendor/github.com/vmware/govmomi/object.(*DistributedVirtualPortgroup).EthernetCardBackingInfo(0xc42029b080, 0x1e7dea0, 0xc4203d8840, 0x9, 0xc4203394c8, 0xc4201a6c80, 0x1)
	<autogenerated>:446 +0x87
github.com/docker/machine/drivers/vmwarevsphere.(*Driver).Create(0xc420147180, 0x0, 0x0)
	/go/src/github.com/docker/machine/drivers/vmwarevsphere/vsphere.go:576 +0x1625
github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Create(0xc420134fa0, 0x1edb920, 0x1edb920, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:140 +0x78
reflect.Value.call(0xc420140900, 0xc420132210, 0x13, 0x14dc768, 0x4, 0xc42003ff20, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc420140900, 0xc420132210, 0x13, 0xc42002af20, 0x3, 0x3, 0x0, 0x0, 0xc420132330)
	/usr/local/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420137600, 0xc420136240, 0xc42011c0c0, 0xc420139180, 0xc420120640, 0x1124080, 0x1edb920, 0x16, 0x1124080, 0x1edb920, ...)
	/usr/local/go/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:481 +0x404

notifying bugsnag: [Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference
goroutine 56 [running]:
runtime/debug.Stack(0xc4203d8858, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/docker/machine/libmachine/drivers/rpc.(*StandardStack).Stack(0x1edb5a0, 0x121bba0, 0x1eac410, 0x1e78720)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:23 +0x22
github.com/docker/machine/libmachine/drivers/rpc.trapPanic(0xc420339ae0)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:129 +0xa5
panic(0x121bba0, 0x1eac410)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/docker/machine/vendor/github.com/vmware/govmomi/object.DistributedVirtualPortgroup.EthernetCardBackingInfo(0xc420096000, 0xc420370580, 0x1b, 0xc420370640, 0x11, 0xc4204b2500, 0x19, 0x1e7dea0, 0xc4203d8840, 0x30, ...)
	/go/src/github.com/docker/machine/vendor/github.com/vmware/govmomi/object/distributed_virtual_portgroup.go:52 +0x24f
github.com/docker/machine/vendor/github.com/vmware/govmomi/object.(*DistributedVirtualPortgroup).EthernetCardBackingInfo(0xc42029b080, 0x1e7dea0, 0xc4203d8840, 0x9, 0xc4203394c8, 0xc4201a6c80, 0x1)
	<autogenerated>:446 +0x87
github.com/docker/machine/drivers/vmwarevsphere.(*Driver).Create(0xc420147180, 0x0, 0x0)
	/go/src/github.com/docker/machine/drivers/vmwarevsphere/vsphere.go:576 +0x1625
github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Create(0xc420134fa0, 0x1edb920, 0x1edb920, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:140 +0x78
reflect.Value.call(0xc420140900, 0xc420132210, 0x13, 0x14dc768, 0x4, 0xc42003ff20, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0xc420140900, 0xc420132210, 0x13, 0xc42002af20, 0x3, 0x3, 0x0, 0x0, 0xc420132330)
	/usr/local/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc420137600, 0xc420136240, 0xc42011c0c0, 0xc420139180, 0xc420120640, 0x1124080, 0x1edb920, 0x16, 0x1124080, 0x1edb920, ...)
	/usr/local/go/src/net/rpc/server.go:387 +0x144
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:481 +0x404
]
```

**Comment by chrispoupart** [comment]
I am running into a similar issue.  When running with version 0.16.1, I get the following:

```
...
(docker-vsphere) adding network: VLAN 385
(docker-vsphere) Reconfiguring VM
(docker-vsphere) Waiting for VMware Tools to come online...
Error creating machine: Error in driver during machine creation: No IP despite waiting for one - check DHCP status
notifying bugsnag: [Error creating machine: Error in driver during machine creation: No IP despite waiting for one - check DHCP status]
```

If I investigate the machine that was created, it was not created with a NIC, despite it seeming to pass the "adding network" phase.
