### ISSUE TITLE
'MobyLinuxVM' failed to start. (Virtual machine ID 9261B426-281D-4D03-B712-E4394639ADAD) at Start-MobyLinuxVM, <No file>: line 300

### ISSUE THREAD

**Issue by AdamClary** [docker/machine#4502]
I am currently running on the windows containers version of docker and when I try to switch to the Linux containers I get the following error message.

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 9261B426-281D-4D03-B712-E4394639ADAD)
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass23_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 264
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

I have uploaded the diagnostics and this is the diagnostic ID:  3C498172-BE0A-41F8-9881-1B0ADA8CA5F0/2018-06-05_12-55-28

**Comment by AdamClary** [comment]
I have been trying to solve this for the past two days with no success. Any help would be appreciated
