### ISSUE TITLE
vmware/govmomi needs update to support NSX-Networks

### ISSUE THREAD

**Issue by Nold360** [docker/machine#4581]
# General
We tried deploying VMs in our VSphere environment using Rancher, which uses the latest docker-machine 0.15 but it didn't work. It turned out, that the cause is that we have NSX enabled in our VSphere environment & it's not yet supported by the underlying vmare/govmomi module. 

Error Message: **panic: not implemented for type mo.OpaqueNetwork**

# Details
The 'vendor/github.com/vmware/govmomi' module needs an update to (for example) support NSX-Networks. This has been fixed in upstream in [November 2016!](https://github.com/vmware/govmomi/commit/128b352e4a8ab97ebd04a8c4229e13cf18017ece#diff-a1cb7febf6da1753eb791eb8980e2154)

So i pulled the latest release into [my fork](https://github.com/Nold360/machine) (using git submodule) and tried compiling docker-machine.

There were a few API changes, too. I tried fixing them but since I've never coded go before, i have no idea if those are correct. See https://github.com/Nold360/machine/commit/5f287edd63a4042dbb889d5e8a6ff7de28ab8d8a

In the end, I still got an error 401 when docker-machine tries uploading the ISO-File.

# Debug  Output 
## Options
``` bash
docker-machine --debug create -d vmwarevsphere \
    --engine-install-url https://releases.rancher.com/install-docker/17.03.2.sh \
    --vmwarevsphere-datacenter $DC \
    --vmwarevsphere-password $PASSWD \
    --vmwarevsphere-vcenter $VCENTER $ \
    --vmwarevsphere-hostsystem $HOSTSYSTEM \
    --vmwarevsphere-username $ACCOUNT$ \
    --vmwarevsphere-vcenter-port 443 \
    --vmwarevsphere-boot2docker-url https://releases.rancher.com/os/latest/rancheros-vmware.iso \
    --vmwarevsphere-disk-size 30000 \
    --vmwarevsphere-folder /Container \
    --vmwarevsphere-network $NETWORK \
    --vmwarevsphere-cpu-count 2 \
    --vmwarevsphere-datastore $DATASTORE  \
    --vmwarevsphere-memory-size 2048 \
    docker-machine-vm
```

## Latest (0.15) Upstream Version
```
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver vmwarevsphere
Plugin server listening at address 127.0.0.1:37311
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(docker-machine-vm) Calling .GetMachineName
(docker-machine-vm) Calling .DriverName
(docker-machine-vm) Calling .GetCreateFlags
(docker-machine-vm) Calling .SetConfigFromFlags
Reading certificate data from /home/noroot/.docker/machine/certs/ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from /home/noroot/.docker/machine/certs/cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(docker-machine-vm) Calling .PreCreateCheck
(docker-machine-vm) DBG | Connecting to vSphere for pre-create checks...
(docker-machine-vm) DBG | panic: not implemented for type mo.OpaqueNetwork
(docker-machine-vm) DBG |
(docker-machine-vm) DBG | goroutine 24 [running]:
(docker-machine-vm) DBG | github.com/docker/machine/vendor/github.com/vmware/govmomi/list.ToElement(0x7f1816de7840, 0xc42013d340, 0xc420408e60, 0xd, 0xc42013d340, 0x1f, 0x1533e40, 0xc42013cfc0)
(docker-machine-vm) DBG |       /go/src/github.com/docker/machine/vendor/github.com/vmware/govmomi/list/lister.go:95 +0xe27
(docker-machine-vm) DBG | github.com/docker/machine/vendor/github.com/vmware/govmomi/list.Lister.ListFolder(0xc4201675f0, 0xc420092e48, 0x6, 0xc420092e70, 0x8, 0xc420408e60, 0xd, 0x1, 0x153a700, 0xc4200cbd80, ...)
(docker-machine-vm) DBG |       /go/src/github.com/docker/machine/vendor/github.com/vmware/govmomi/list/lister.go:250 +0x7ad
(docker-machine-vm) DBG | github.com/docker/machine/vendor/github.com/vmware/govmomi/list.Lister.List(0xc4201675f0, 0xc420092e48, 0x6, 0xc420092e70, 0x8, 0xc420408e60, 0xd, 0x1, 0x153a700, 0xc4200cbd80, ...)
(docker-machine-vm) DBG |       /go/src/github.com/docker/machine/vendor/github.com/vmware/govmomi/list/lister.go:166 +0xc0
(docker-machine-vm) DBG | github.com/docker/machine/vendor/github.com/vmware/govmomi/list.Recurser.Recurse(0xc4201675f0, 0x1530001, 0x153a700, 0xc4200cbd80, 0xc420408e60, 0xd, 0x1531140, 0xc4205073c0, 0xc4203a21d0, 0x1, ...)
(docker-machine-vm) DBG |       /go/src/github.com/docker/machine/vendor/github.com/vmware/govmomi/list/recurser.go:64 +0x147
(docker-machine-vm) DBG | github.com/docker/machine/vendor/github.com/vmware/govmomi/find.(*Finder).find(0xc420167620, 0x153a700, 0xc4200cbd80, 0xc420495838, 0xc420168000, 0xc420032d00, 0x13, 0x0, 0x38, 0xc4204a8000, ...)
(docker-machine-vm) DBG |       /go/src/github.com/docker/machine/vendor/github.com/vmware/govmomi/find/finder.go:96 +0x25e
(docker-machine-vm) DBG | github.com/docker/machine/vendor/github.com/vmware/govmomi/find.(*Finder).NetworkList(0xc420167620, 0x153a700, 0xc4200cbd80, 0xc420032d00, 0x13, 0x17, 0xc42000c288, 0x1, 0x1, 0x0)
(docker-machine-vm) DBG |       /go/src/github.com/docker/machine/vendor/github.com/vmware/govmomi/find/finder.go:548 +0xa0
(docker-machine-vm) DBG | github.com/docker/machine/vendor/github.com/vmware/govmomi/find.(*Finder).Network(0xc420167620, 0x153a700, 0xc4200cbd80, 0xc420032d00, 0x13, 0x17, 0xc4204a8000, 0x0, 0x0)
(docker-machine-vm) DBG |       /go/src/github.com/docker/machine/vendor/github.com/vmware/govmomi/find/finder.go:580 +0x5a
(docker-machine-vm) DBG | github.com/docker/machine/vendor/github.com/vmware/govmomi/find.(*Finder).NetworkOrDefault(0xc420167620, 0x153a700, 0xc4200cbd80, 0xc420032d00, 0x13, 0xc4204a8000, 0x0, 0x0, 0x0)
(docker-machine-vm) DBG |       /go/src/github.com/docker/machine/vendor/github.com/vmware/govmomi/find/finder.go:603 +0x60
(docker-machine-vm) DBG | github.com/docker/machine/drivers/vmwarevsphere.(*Driver).PreCreateCheck(0xc420191180, 0x0, 0x0)
(docker-machine-vm) DBG |       /go/src/github.com/docker/machine/drivers/vmwarevsphere/vsphere.go:377 +0x44a
(docker-machine-vm) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).PreCreateCheck(0xc42000a960, 0x1efbc38, 0x1efbc38, 0x0, 0x0)
(docker-machine-vm) DBG |       /go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:201 +0x33
(docker-machine-vm) DBG | reflect.Value.call(0xc42007a720, 0xc42000c360, 0x13, 0x141760a, 0x4, 0xc42006bf18, 0x3, 0x3, 0xc4200cb780, 0x0, ...)
(docker-machine-vm) DBG |       /usr/local/go/src/reflect/value.go:447 +0x969
(docker-machine-vm) DBG | reflect.Value.Call(0xc42007a720, 0xc42000c360, 0x13, 0xc42004df18, 0x3, 0x3, 0x0, 0x0, 0x0)
(docker-machine-vm) DBG |       /usr/local/go/src/reflect/value.go:308 +0xa4
(docker-machine-vm) DBG | net/rpc.(*service).call(0xc420076e40, 0xc42017a1e0, 0xc420034550, 0xc420034560, 0xc420187580, 0xc42011d680, 0x104fea0, 0x1efbc38, 0x16, 0x104fea0, ...)
(docker-machine-vm) DBG |       /usr/local/go/src/net/rpc/server.go:384 +0x14e
(docker-machine-vm) DBG | created by net/rpc.(*Server).ServeCodec
(docker-machine-vm) DBG |       /usr/local/go/src/net/rpc/server.go:480 +0x43a
Error with pre-create check: "unexpected EOF"
notifying bugsnag: [Error with pre-create check: "unexpected EOF"]
```

## Modified Version
```

Found binary path at ./bin/docker-machine
Launching plugin server for driver vmwarevsphere
Plugin server listening at address 127.0.0.1:45907
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at ./bin/docker-machine
Launching plugin server for driver vmwarevsphere
Plugin server listening at address 127.0.0.1:43931
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(docker-machine-vm) Calling .GetMachineName
(docker-machine-vm) Calling .DriverName
(docker-machine-vm) Calling .GetCreateFlags
(docker-machine-vm) Calling .SetConfigFromFlags
Reading certificate data from /home/noroot/.docker/machine/certs/ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from /home/noroot/.docker/machine/certs/cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(docker-machine-vm) Calling .PreCreateCheck
(docker-machine-vm) DBG | Connecting to vSphere for pre-create checks...
(docker-machine-vm) Calling .GetConfigRaw
Creating machine...
(docker-machine-vm) Calling .Create
(docker-machine-vm) Downloading /home/noroot/.docker/machine/cache/boot2docker.iso from https://releases.rancher.com/os/latest/rancheros-vmware.iso...
(docker-machine-vm) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(docker-machine-vm) Generating SSH Keypair...
(docker-machine-vm) Creating VM...
(docker-machine-vm) Uploading Boot2docker ISO ...
Error creating machine: Error in driver during machine creation: 401 Unauthorized
```

**Comment by Ern-st** [comment]
@Nold360 you might want to take a look at ranchers docker-machine fork, from my limited testing it works fine. They're yet to merge it into the master branch but you can try and build the binary from this branch https://github.com/rancher/machine/pull/16

**Comment by Nold360** [comment]
@Ern-st yea, I've noticed that but didn't find the time to try it, though. But I will asap! Thanks
