### ISSUE TITLE
azure driver - create - Error with pre-create check: "unexpected EOF" 

### ISSUE THREAD

**Issue by mdonepudi** [docker/machine#4690]
On docker-machine version 0.15.0 (binaries and GoLang libraries), using azure driver, machine create ends up with 'unexpected EOF'.

section of the related debug logs below

> (docker-machine-lib-test113) DBG | Already registered for "Microsoft.Compute"
(docker-machine-lib-test113) DBG | Already registered for "Microsoft.Network"
(docker-machine-lib-test113) DBG | Already registered for "Microsoft.Storage"
(docker-machine-lib-test113) DBG | Docker port is configured as 2376
(docker-machine-lib-test113) DBG | Swarm host is not configured.
(docker-machine-lib-test113) DBG | Total NSG rules: 2
(docker-machine-lib-test113) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(docker-machine-lib-test113) DBG | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9eca36]
(docker-machine-lib-test113) DBG |
(docker-machine-lib-test113) DBG | goroutine 24 [running]:
(docker-machine-lib-test113) DBG | github.com/docker/machine/drivers/azure.(*Driver).PreCreateCheck(0xc420286000, 0xc42017b300, 0xc42017b320)
(docker-machine-lib-test113) DBG |        /go/src/github.com/docker/machine/drivers/azure/azure.go:316 +0x146
(docker-machine-lib-test113) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).PreCreateCheck(0xc42017a880, 0x1efbc38, 0x1efbc38, 0x0, 0x0)
(docker-machine-lib-test113) DBG |        /go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:201 +0x33
(docker-machine-lib-test113) DBG | reflect.Value.call(0xc420086720, 0xc420178338, 0x13, 0x141760a, 0x4, 0xc42006ff18, 0x3, 0x3, 0xc42007a040, 0x0, ...)
(docker-machine-lib-test113) DBG |        /usr/local/go/src/reflect/value.go:447 +0x969
(docker-machine-lib-test113) DBG | reflect.Value.Call(0xc420086720, 0xc420178338, 0x13, 0xc420051718, 0x3, 0x3, 0x0, 0x0, 0x0)
(docker-machine-lib-test113) DBG |        /usr/local/go/src/reflect/value.go:308 +0xa4
(docker-machine-lib-test113) DBG | net/rpc.(*service).call(0xc420170d80, 0xc4201720f0, 0xc4200328d0, 0xc4200328e0, 0xc420189580, 0xc42017ae80, 0x104fea0, 0x1efbc38, 0x16, 0x104fea0, ...)
(docker-machine-lib-test113) DBG |        /usr/local/go/src/net/rpc/server.go:384 +0x14e
(docker-machine-lib-test113) DBG | created by net/rpc.(*Server).ServeCodec
(docker-machine-lib-test113) DBG |        /usr/local/go/src/net/rpc/server.go:480 +0x43a
Error creating a machine:  Error with pre-create check: "unexpected EOF"
Making call to close driver server
(docker-machine-lib-test113) Calling .Close
Failed to make call to close driver server: connection is shut down
Making call to close connection to plugin binary

**Comment by mdonepudi** [comment]
same issue with v0.16.0
