### ISSUE TITLE
subcommands start, stop, restart, kill, upgrade will crash while no active machine

### ISSUE THREAD

**Issue by TrumanLing** [docker/machine#771]
```console
$ sudo ./docker-machine_linux-amd64 ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM
dev1            virtualbox   Stopped
dev2            virtualbox   Stopped
dev3            virtualbox   Running   tcp://192.168.99.100:2376
```

Detailed error messages are as following:

```console
$ sudo ./docker-machine_linux-amd64 kill
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4072f9]

goroutine 16 [running]:
runtime.panic(0xa4ad00, 0x10358f3)
        /usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
main.runActionForeachMachine(0xae4210, 0x4, 0xc208089548, 0x1, 0x1)
        /go/src/github.com/docker/machine/commands.go:606 +0x599
main.runActionWithContext(0xae4210, 0x4, 0xc208056600, 0x0, 0x0)
        /go/src/github.com/docker/machine/commands.go:656 +0x2d4
main.cmdKill(0xc208056600)
        /go/src/github.com/docker/machine/commands.go:680 +0x3e
github.com/codegangsta/cli.Command.Run(0xae4210, 0x4, 0x0, 0x0, 0xaf85f0, 0xe, 0xbde1b0, 0x5b, 0x0, 0x0, ...)
        /go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2
github.com/codegangsta/cli.(*App).Run(0xc20802a410, 0xc20800e000, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea
main.main()
        /go/src/github.com/docker/machine/main.go:67 +0x7cd

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
        /usr/src/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
        /usr/src/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
        /usr/src/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
        /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
        /usr/src/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
        /usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32
```

**Comment by ehazlett** [comment]
This should be fixed.  Please re-open if you continue to have issues.  Thanks!
