### ISSUE TITLE
docker-machine ssh panics without active machine set

### ISSUE THREAD

**Issue by slashk** [docker/machine#831]
docker-machine panics with a runtime error if the active machine is not set.

```
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
builder            virtualbox   Running   tcp://192.168.99.100:2376
dev                virtualbox   Stopped
$
$ docker-machine ssh
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7411]

goroutine 16 [running]:
runtime.panic(0x6505a0, 0xa528e4)
	/usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
main.cmdSsh(0x208b8c900)
	/go/src/github.com/docker/machine/commands.go:587 +0x791
github.com/codegangsta/cli.Command.Run(0x6eefd0, 0x3, 0x0, 0x0, 0x7a4690, 0x2f, 0x7e03b0, 0x57, 0x0, 0x0, ...)
	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2
github.com/codegangsta/cli.(*App).Run(0x208b62410, 0x208b46000, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea
main.main()
	/go/src/github.com/docker/machine/main.go:67 +0x7cd

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
	/usr/src/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
	/usr/src/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
	/usr/src/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
	/usr/src/go/src/pkg/os/signal/signal_unix.go:19
created by os/signal.init·1
	/usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32
```

**Comment by nathanleclaire** [comment]
@ehazlett I think this can be closed now?

**Comment by ehazlett** [comment]
Closing as #831 was merged.
