### ISSUE TITLE
[Mac OSX10] unexpected fault address 0xb01dfacedebac1e

### ISSUE THREAD

**Issue by dwamara** [docker/machine#864]
Trying to run "docker-machine create --driver virtualbox dev" on my machine, I get following error that I have no clue about.

```
Mac-7c6d628bedf4:~ daolwin$ docker-machine create --driver virtualbox dev
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x661cb]

goroutine 16 [running]:
runtime.throw(0xad4c53)
	/usr/src/go/src/pkg/runtime/panic.c:520 +0x69 fp=0x208c60150 sp=0x208c60138
runtime.sigpanic()
	/usr/src/go/src/pkg/runtime/os_darwin.c:457 +0x13f fp=0x208c60168 sp=0x208c60150
fmt.(*pp).doPrintf(0x208bfa270, 0x2065687420676e69, 0x6974706f20494c43, 0x208c606a8, 0x1, 0x1)
	/usr/src/go/src/pkg/fmt/print.go:1053 +0x9b fp=0x208c60528 sp=0x208c60168
fmt.Sprintf(0x2065687420676e69, 0x6974706f20494c43, 0x208c606a8, 0x1, 0x1, 0x0, 0x0)
	/usr/src/go/src/pkg/fmt/print.go:203 +0x7c fp=0x208c60578 sp=0x208c60528
github.com/docker/machine/utils.(*B2dUtils).GetLatestBoot2DockerReleaseURL(0x208c140c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/utils/b2d.go:62 +0x1e7 fp=0x208c607d0 sp=0x208c60578
github.com/docker/machine/drivers/virtualbox.(*Driver).Create(0x208cca360, 0x0, 0x0)
	/go/src/github.com/docker/machine/drivers/virtualbox/virtualbox.go:155 +0x1ddc fp=0x208c61240 sp=0x208c607d0
main.(*Host).Create(0x208c29080, 0x7fff5fbffa32, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/machine/host.go:386 +0xcc fp=0x208c612c8 sp=0x208c61240
main.(*Store).Create(0x208cc51a0, 0x7fff5fbffa32, 0x3, 0x208cd5c56, 0xa, 0x2208bd4ea0, 0x208c28fc0, 0x39, 0x0, 0x0)
	/go/src/github.com/docker/machine/store.go:63 +0x63b fp=0x208c614d8 sp=0x208c612c8
main.cmdCreate(0x208c28fc0)
	/go/src/github.com/docker/machine/commands.go:318 +0x523 fp=0x208c61660 sp=0x208c614d8
github.com/codegangsta/cli.Command.Run(0x73f3f0, 0x6, 0x0, 0x0, 0x784f70, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2 fp=0x208c619a8 sp=0x208c61660
github.com/codegangsta/cli.(*App).Run(0x208bfa4e0, 0x208bd0000, 0x5, 0x5, 0x0, 0x0)
	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea fp=0x208c61c30 sp=0x208c619a8
main.main()
	/go/src/github.com/docker/machine/main.go:67 +0x7cd fp=0x208c61f50 sp=0x208c61c30
runtime.main()
	/usr/src/go/src/pkg/runtime/proc.c:247 +0x11a fp=0x208c61fa8 sp=0x208c61f50
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445 fp=0x208c61fb0 sp=0x208c61fa8
created by _rt0_go
	/usr/src/go/src/pkg/runtime/asm_amd64.s:97 +0x120

goroutine 19 [finalizer wait]:
runtime.park(0x27cf0, 0xad8b38, 0xad6cc9)
	/usr/src/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xad8b38, 0xad6cc9)
	/usr/src/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/src/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
	/usr/src/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init•1
	/usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32
Mac-7c6d628bedf4:~ daolwin$ 
```

**Comment by sthulb** [comment]
Hi @dwamara. Could you give any more information around commit hash, conditions of what could contribute to this?

**Comment by nathanleclaire** [comment]
Hi @dwamara, just curious, what was your install method?  curl+chmod the binary from our official release page, package manager, etc.?

**Comment by dwamara** [comment]
I had a version from 3 weeks ago I think, I downloaded the latest version docker-machine_darwin-amd64 (from https://docs.docker.com/machine/) and I now got 
``
Mac-7c6d628bedf4:Work daolwin$ ./docker-machine_darwin-amd64 create --driver virtualbox dev
INFO[0001] Downloading boot2docker.iso to /Volumes/Data/Users/daolwin/.docker/machine/cache/boot2docker.iso... 
INFO[0085] Creating SSH key...                          
INFO[0085] Creating VirtualBox VM...                    
ERRO[0101] Error creating machine: exit status 1        
WARN[0101] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0101] Error creating machine                       
``

**Comment by hairyhenderson** [comment]
@dwamara - you could try adding `--debug` to get more information:

```
$ ./docker-machine_darwin-amd64 --debug create --driver virtualbox dev
```

**Comment by dwamara** [comment]
Here you go
```
INFO[0003] Creating VirtualBox VM...                    
DEBU[0003] Creating 20000 MB hard disk image...         
Converting from raw image file="stdin" to file="/Volumes/Data/Users/daolwin/.docker/machine/machines/dev/disk.vmdk"...
Creating dynamic image with size 20971520000 bytes (20000MB)...
DEBU[0019] executing: /usr/bin/VBoxManage createvm --basefolder /Volumes/Data/Users/daolwin/.docker/machine/machines/dev --name dev --register 
DEBU[0020] STDOUT: Virtual machine 'dev' is created and registered.
UUID: b9dc029a-f863-40c2-a270-4397cf20930b
Settings file: '/Volumes/Data/Users/daolwin/.docker/machine/machines/dev/dev/dev.vbox'
 
DEBU[0020] STDERR:                                      
DEBU[0020] executing: /usr/bin/VBoxManage modifyvm dev --firmware bios --bioslogofadein off --bioslogofadeout off --natdnshostresolver1 on --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 4 --memory 1024 --acpi on --ioapic on --rtcuseutc on --cpuhotplug off --pae on --synthcpu off --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd 
DEBU[0020] STDOUT:                                      
DEBU[0020] STDERR:                                      
DEBU[0020] executing: /usr/bin/VBoxManage modifyvm dev --nic1 nat --nictype1 virtio --cableconnected1 on 
DEBU[0020] STDOUT:                                      
DEBU[0020] STDERR:                                      
DEBU[0020] executing: /usr/bin/VBoxManage modifyvm dev --natpf1 ssh,tcp,127.0.0.1,59432,,22 
DEBU[0020] STDOUT:                                      
DEBU[0020] STDERR:                                      
DEBU[0020] executing: /usr/bin/VBoxManage list hostonlyifs 
DEBU[0020] STDOUT:                                      
DEBU[0020] STDERR:                                      
DEBU[0020] executing: /usr/bin/VBoxManage hostonlyif create 
DEBU[0020] STDOUT:                                      
DEBU[0020] STDERR: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg*, int, int*)" at line 66 of file VBoxManageHostonly.cpp
 
ERRO[0020] Error creating machine: exit status 1        
WARN[0020] You will want to check the provider to make sure the machine and associated resources were properly removed. 
FATA[0020] Error creating machine                       
```

**Comment by dwamara** [comment]
It looks like I closed it by mistake yesternite.

**Comment by hairyhenderson** [comment]
@dwamara - Looks to me like there's an issue with how VirtualBox is installed... Does VBox work for other purposes?

This forum posting from virtualbox.org might be relevant: https://forums.virtualbox.org/viewtopic.php?f=8&t=55347

**Comment by nathanleclaire** [comment]
@dwamara Are you still getting this with 0.3.0?

**Comment by dmp42** [comment]
@dwamara are you still seeing this?

**Comment by dwamara** [comment]
No, not since I updated the VirtualBox I was using. 

Daniel Wamara
Chief Executive Officer 
DWI Technologies
