### ISSUE TITLE
[CoreOS] docker-machine create -> panic: runtime error: index out of range

### ISSUE THREAD

**Issue by AxelVoitier** [docker/machine#996]
Hello,

I tried to create a machine using openstack and a coreos image. I used docker-machine v0.2.0-rc3. I get the following error:

```
$ ./docker-machine create -d openstack --openstack-flavor-name="m1.small" --openstack-image-name="CoreOS-607.0.0" --openstack-ssh-user="core" cvl-av-test1

INFO[0002] Creating machine...                          
panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0xa6a0c0, 0x106d71c)
	/usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/docker/machine/libmachine/provision.parseLine(0xc20836cb20, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/provision/os_release.go:62 +0x323
github.com/docker/machine/libmachine/provision.(*OsRelease).ParseOsRelease(0xc20828c320, 0xc20833ac00, 0xc8, 0x600, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/provision/os_release.go:70 +0x210
github.com/docker/machine/libmachine/provision.NewOsRelease(0xc20833ac00, 0xc8, 0x600, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/provision/os_release.go:83 +0x80
github.com/docker/machine/libmachine/provision.DetectProvisioner(0x7f7cb9d68080, 0xc208084000, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/provision/provisioner.go:85 +0x3be
github.com/docker/machine/libmachine.(*Host).Create(0xc208001930, 0x7ffcab88ada2, 0xc, 0x0, 0x0)
	/go/src/github.com/docker/machine/libmachine/host.go:117 +0x204
github.com/docker/machine/libmachine.(*Machine).Create(0xc208062130, 0x7ffcab88ada2, 0xc, 0xc2080620c5, 0x9, 0xc2080826c0, 0x7f7cb9d67f40, 0xc2080523c0, 0x0, 0x0, ...)
	/go/src/github.com/docker/machine/libmachine/machine.go:59 +0x565
main.cmdCreate(0xc2080523c0)
	/go/src/github.com/docker/machine/commands.go:420 +0xa08
github.com/codegangsta/cli.Command.Run(0xb042b0, 0x6, 0x0, 0x0, 0xb473b0, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0xeb2
github.com/codegangsta/cli.(*App).Run(0xc208000340, 0xc20800e000, 0x8, 0x8, 0x0, 0x0)
	/go/src/github.com/docker/machine/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xaea
main.main()
	/go/src/github.com/docker/machine/main.go:71 +0x5a3

goroutine 19 [finalizer wait, 4 minutes]:
runtime.park(0x422530, 0x1084af8, 0x106f9c9)
	/usr/src/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x1084af8, 0x106f9c9)
	/usr/src/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/src/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 5 minutes]:
os/signal.loop()
	/usr/src/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/src/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 17 [syscall, 5 minutes]:
runtime.goexit()
	/usr/src/go/src/pkg/runtime/proc.c:1445
```

(Sorry, I am no good at interpreting a go stacktrace ;( can edit the issue title if you know a more descriptive one ;) )

**Comment by ehazlett** [comment]
@AxelVoitier Thanks for reporting!  Right now we only support Ubuntu.  We are working on expanding host OS capabilities in 0.3.0.  Would you mind trying with Ubuntu 14.04 amd64?

**Comment by AxelVoitier** [comment]
Ah! I was actually looking for a recommendation on what OS image I should try with with the openstack driver. Yes, I am happy to test with Ubuntu.

**Comment by AxelVoitier** [comment]
Indeed, works fine with Ubuntu :).
You can keep the issue open if you want to support CoreOS one day. I am fine with ubuntu for the moment :).

**Comment by ehazlett** [comment]
Thanks for the feedback!  I am going to close this for now.  Feel free to open a new issue when we get the expanded provisioning.

**Comment by l15k4** [comment]
Hey, is CoreOS going to be supported eventually? Any update on this?
